### ISSUE TITLE
robodoc AUTHOR tag

### ISSUE THREAD

**Issue by mdedwards** [mdedwards/slippery-chicken#10]
see if we can get robodoc to pull out the AUTHOR tag (e.g. on pause-last method) and pop it into the html/pdf

**Comment by danieljamesross** [comment]
Guess we'd need an IF statement to see if there was an original AUTHOR tag. If not, then defaults to you and Shaun?

**Comment by mdedwards** [comment]
nah, it's a robodoc config thing, nothing to do with lisp. have made a task for this but don't hold your breath ;)

**Comment by danieljamesross** [comment]
It's a C++ thing though, right?

**Comment by mdedwards** [comment]
robodoc is, yes. leave it with me.

**Comment by mdedwards** [comment]
OK I've successfully added the AUTHOR tag so these will show up in robodoc webpages and PDFs in the next release.
