### ISSUE TITLE
_config.yml?

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#100]
Hello,

do we need this file (`_config.yml`) in the root dir?

Best
Ruben

**Comment by mdedwards** [comment]
Aha, you're wanting to slim down even more? :)

That was written by GitHub itself I think, way back. Just sets the theme. I can't live without it.

Best, Michael

**Comment by rubenphilipp** [comment]
Ah, I was completely ignorant of the fact that the repo uses GitHub pages. Now the file makes sense for me. :)
