### ISSUE TITLE
Error after updating to SBCL 2.4.9

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#102]
Hello,

I was, finally, brave enough to update my SBCL from version 2.3.0 to the latest 2.4.9 (MacOS 14.7 😵‍💫). Unfortunately, I encounter the following error when running the test-suite:

```
PITCH: frequency: 174.614, midi-note: 53, midi-channel: 4 
       pitch-bend: 0.0 
       degree: 106, data-consistent: T, white-note: E3
       nearest-chromatic: ES3
       src: 0.66741997, src-ref-pitch: C4, score-note: ES3 
       qtr-sharp: NIL, qtr-flat: NIL, qtr-tone: NIL,  
       micro-tone: NIL, 
       sharp: NIL, flat: NIL, natural: NIL, 
       octave: 3, c5ths: 0, no-8ve: ES, no-8ve-no-acc: E
       show-accidental: T, white-degree: 30, 
       accidental: S, 
       accidental-in-parentheses: NIL, marks: NIL, 
       marks-before: NIL, amplitude: NIL
LINKED-NAMED-OBJECT: previous: NIL, 
                     this: NIL, 
                     next: NIL
NAMED-OBJECT: id: ES3, tag: NIL, 
data: ES3
**************
 
pitch::cmn-get-cmn-12th-tone-accidentals: what pitch was that?
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry EVAL of current toplevel form.
 1: [CONTINUE] Ignore error and continue loading file "/Users/rubenphilipp/lisp/slippery-chicken/tests/sc-test-suite.lsp".
 2: [ABORT] Abort loading file "/Users/rubenphilipp/lisp/slippery-chicken/tests/sc-test-suite.lsp".
 3: [RETRY] Retry SLY mREPL evaluation request.
 4: [*ABORT] Return to SLY's top level.
 5: [ABORT] abort thread (#<THREAD tid=5379 "sly-channel-1-mrepl-remote-1" RUNNING {7004F60DC3}>)

Backtrace:
 0: ((:METHOD GET-CMN-12TH-TONE-ACCIDENTALS (PITCH))  ..) [fast-method]
 1: ((:METHOD GET-CMN-DATA (PITCH))  ..) [fast-method]
 2: ((:METHOD GET-CMN-DATA (EVENT))  ..) [fast-method]
 3: ((:METHOD GET-CMN-DATA (RTHM-SEQ-BAR))  ..) [fast-method]
 4: ((:METHOD GET-CMN-DATA (SEQUENZ))  ..) [fast-method]
 5: ((:METHOD GET-CMN-DATA (PLAYER-SECTION))  ..) [fast-method]
 6: ((:METHOD GET-CMN-DATA (PIECE))  ..) [fast-method]
 7: ((:METHOD CMN-DISPLAY (PIECE))  ..) [fast-method]
 8: ((SB-PCL::EMF CMN-DISPLAY) #<unused argument> #<unused argument>  ..)
 9: ((:METHOD CMN-DISPLAY (SLIPPERY-CHICKEN))  ..) [fast-method]
10: ((SB-PCL::EMF CMN-DISPLAY) #<unused argument> #<unused argument>  ..)
11: (TEST-RING-MOD-PIECE)
12: ((LAMBDA NIL :IN "/Users/rubenphilipp/lisp/slippery-chicken/tests/sc-test-suite.lsp"))
13: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SC-TEST-TEST-ALL) #<NULL-LEXENV>)
14: (SB-INT:SIMPLE-EVAL-IN-LEXENV (IF (SC-TEST-TEST-ALL) (PROGN (SETF *SC-TEST-METH-AND-FUNC-TESTS-STATE* "- ALL METHOD AND FUNCTION TESTS PASSED.") (FORMAT T "~%~%~a~%~%" *SC-TEST-METH-AND-FUNC-TESTS-STA..
15: (SB-EXT:EVAL-TLF (IF (SC-TEST-TEST-ALL) (PROGN (SETF *SC-TEST-METH-AND-FUNC-TESTS-STATE* "- ALL METHOD AND FUNCTION TESTS PASSED.") (FORMAT T "~%~%~a~%~%" *SC-TEST-METH-AND-FUNC-TESTS-STATE*)) (PROGN ..
16: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (IF (SC-TEST-TEST-ALL) (PROGN (SETF *SC-TEST-METH-AND-FUNC-TESTS-STATE* "- ALL METHOD AND FUNCTION TESTS PASSED.") (FORMAT T "~%~%~a~%~%" *SC-TES..
17: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (IF (SC-TEST-TEST-ALL) (PROGN (SETF *SC-TEST-METH-AND-FUNC-TESTS-STATE* "- ALL METHOD AND FUNCTION TESTS PASS..
18: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {11389196B}> #<SB-C::SOURCE-INFO {7003810763}> SB-C::INPUT-ERROR-IN-LOAD..
19: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /Users/rubenphilipp/lisp/slippery-chicken/tests/sc-test-suite.lsp" {7003810533}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
 --more--
```

This might be an easy one, but I did not find time yet to investigate. Maybe @mdedwards might already know the suspect… 

Best
Ruben

**Comment by mdedwards** [comment]
Hallo Ruben, I’m still on sbcl 2.3.4 (MacOS 14.6.1) and brew won’t update sbcl, so I can’t check this for now. Seems strange though as 12th-tone accidentals are very old, as is that test. Maybe we’ll find a moment to look at this together. Best, Michael

**Comment by rubenphilipp** [comment]
Alright. I've quickly downgraded to SBCL 2.3.9 (couldn't install 2.3.4) but still get the same error. Let's investigate this later maybe.

Best
Ruben

**Comment by rubenphilipp** [comment]
Another update:

it seems as if the problem only occurs when the pitch applied to `get-cmn-data` (which invokes `get-cmn-12th-tone-accidentals`) is enharmonically equivalent to another "white-key" pitch (e.g. *bs* or *ff*). With this in mind, it is less surprising that the error in `get-cmn-12th-tone-accidentals` occurs as the `cond` statement in `get-cmn-data` should always default to the `t` case, since -- as far as I know -- pitches such as *ff* are, by their slots, neither "sharp", nor "flat" or "natural". Thus, `get-cmn-data` tries to find a 12th-tone-accidental (which is the `t`-case) which obviously causes the error in question (cf. the `cond` in `get-cmn-data` https://github.com/mdedwards/slippery-chicken/blob/e883b61b73d75121c410200106f1310621fa67dd/src/pitch.lsp#L2106). 
I wonder why this problem never occurred before. Do you think we can fix it by improving the `cond` in `get-cmn-data`?

Best
Ruben

**Comment by mdedwards** [comment]
Maybe some update to CM (or even SBCL?) was causing enharmonics to be generated. In any case ‘ff4 was being turned into e4, whose flat slot is of course NIL. I just updated some very old code (is-sharp and is-flat in cm.lsp) to no longer use cm::note and all the tests pass for me.

If it works for you then please close this issue.

**Comment by mdedwards** [comment]
I remember that one, but I also seem to remember that it only happened on your machine. The tests pass for me, including the full tests, as I wrote. Unless I can hit this error myself, there’s nothing I can do about it I fear. I don’t even see which test is failing. All the best, Michael.On 20. Oct 2024, at 14:26, Ruben Philipp ***@***.***> wrote:﻿
Great! Thanks. This test passes now, though I now run into another – probably more annoying – one with run-tests.
While evaluating the form starting at line 21409, column 0
  of (5 6) 1: DQS2 E5 DQS6 AQF6 AQS6 B6 CQS7 DQF7 2: E5 GQS5 AQS5 B5 CQS6 AQS6 4: EQF3 FQS4 E5 AQS5 CS6 AQS6 5: EQS2 AF3 EQF4 A4 DQF5 E5 AQF5 BQF5 AQS6 6: B4 EQF5 BF5 CQS6 DQS6 EQS6 GQS6 AQS6 7: F4 A4 CQS5 EQF5 GQS5 BQS5 CS6 AQS6 23: E5 BF6 D7 EQF7 E7 FQS7 #P"/Users/rubenphilipp/lisp/slippery-chicken/tests/sc-test-suite.lsp":

debugger invoked on a FLOATING-POINT-INVALID-OPERATION in thread
#<THREAD tid=259 "main thread" RUNNING {7004FE0303}>:
  arithmetic error FLOATING-POINT-INVALID-OPERATION signalled

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY   ] Retry EVAL of current toplevel form.
  1: [CONTINUE] Ignore error and continue loading file "/Users/rubenphilipp/lisp/slippery-chicken/tests/sc-test-suite.lsp".
  2: [ABORT   ] Abort loading file "/Users/rubenphilipp/lisp/slippery-chicken/tests/sc-test-suite.lsp".
  3:            Exit debugger, returning to top level.

((FLET SB-UNIX::RUN-HANDLER :IN SB-UNIX::%INSTALL-HANDLER) 8 #.(SB-SYS:INT-SAP #X16F65EB70) #.(SB-SYS:INT-SAP #X16F65EBD8))

I remember being confronted with this one a while ago after updating SBCL, and I think this was the reason why I stuck with 2.3.1 until now. Maybe you've got a clue about this. In the meantime, I will burn some brain-calories pondering about the issue.
Thanks again!
Ruben

**Comment by rubenphilipp** [comment]
Yes, that's particularly strange. I will try to figure this out by myself and let you know when I've found a solution. 
I will close this issue now, as I deem it resolved. 

Have a nice Sunday!
Ruben

**Comment by mdedwards** [comment]
👍On 20. Oct 2024, at 16:00, Ruben Philipp ***@***.***> wrote:﻿
Yes, that's particularly strange. I will try to figure this out by myself and let you know when I've found a solution.
I will close this issue now, as I deem it resolved.
Have a nice Sunday!
Ruben

**Comment by mdedwards** [comment]
Maybe some update to CM (or even SBCL?) was causing enharmonics to be generated. In any case ‘ff4 was being turned into e4, whose flat slot is of course NIL.

I just updated some very old code (is-sharp and is-flat in cm.lsp) to no longer use cm::note and all the tests pass for me (including full).

Best, Michael
