### ISSUE TITLE
AFU

### ISSUE THREAD

**Issue by rhodion50** [mdedwards/slippery-chicken#11]
Hiya
AFU gives an error on my machine (new sc install), undefined function middle-out, can't find it in sc or the AFU code. 

[ERROR.txt](https://github.com/mdedwards/slippery-chicken/files/3320923/ERROR.txt)

**Comment by danieljamesross** [comment]
(middle-out) is in utilities.lsp but you'll need to switch to the "michael" branch, it's not in the "master" release yet.

**Comment by rhodion50** [comment]
Cool thx :)
