### ISSUE TITLE
Mismatch with test-suite

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#12]
https://github.com/mdedwards/slippery-chicken/blob/2a2876dced9fb5cbdf8a82d64643ada218d0cca5/utilities.lsp#L153

The test suite contains new tests e.g. (mins-secs-to-secs "0:00.000")
but there is no provision for these strings in the function.

**Comment by mdedwards** [comment]
there is if you update your src!

**Comment by danieljamesross** [comment]
I did... says I'm up to date on the Michael branch

**Comment by danieljamesross** [comment]
Can't see the relevant code in github desktop either.

**Comment by mdedwards** [comment]
hmm 'git status' tells me I've checked everything in to the michael branch
tests pass for me

that's really weird. just 'touch'ed utilities.lsp, checked back in and I can now see the changes here

not feeling too confident about git/our repo right now...

**Comment by danieljamesross** [comment]
Yes, I wondering the same.

OK, just did a 'git pull' and the utilities.lsp  file showed insertions. Gonna run the test now but will assume it will work. No idea what was stopping me from seeing the changes because I could see the comments and the day/time you made your commits. *scratches chin*

**Comment by mdedwards** [comment]
that's decidedly weird, esp. with that failing test earlier too...not sure what's going on...thankfully we have time machine and other rollback strategies
