### ISSUE TITLE
end-bar arg not working in next-event?

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#13]
https://github.com/mdedwards/slippery-chicken/blob/9015a6fbccb2327deaf5248d901de19af989341f/slippery-chicken.lsp#L2046

Shouldn't the following only return a list containing 1s and 2s?

(progn (next-event +mini+ 'one nil 1 2)
	   (loop for ne = (next-event +mini+ 'one)
		while ne
		collect (bar-num ne)))
=>
(1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4
 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7
 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9 9 9 10 10 10 10 10 10
 10 10 10 10 10 10 11 11 11 11 11 11 11 11 11 11 11 11 12 12 12 12 12 12 12 12
 12 12 12 12 13 13 13 13 13 13 13 13 13 13 13 13 14 14 14 14 14 14 14 14 14 14
 14 14 15 15 15 15 15 15 15 15 15 15 15 15 16 16 16 16 16 16 16 16 16 16 16 16
 17 17 17 17 17 17 17 17 17 17 17 17 18 18 18 18 18 18 18 18 18 18 18 18 19 19
 19 19 19 19 19 19 19 19 19 19 20 20 20 20 20 20 20 20 20 20 20 20)

**Comment by mdedwards** [comment]
nope. the first call to next-event establishes merely where you'll start. the second starts getting the events and that will need the end-bar---you've allowed it to default to the end.

having said that, I don't think there's a RT for this so you might fancy dropping your code into sc-test-suite.lsp :)

see the difference below:

(let ((mini
       (make-slippery-chicken
        '+mini+
        :ensemble '(((cl (b-flat-clarinet :midi-channel 1))
                     (hn (french-horn :midi-channel 2))
                     (vc (cello :midi-channel 3))))
        :set-palette '((1 ((f3 g3 a3 b3 c4 d4 e4 f4 g4 a4 b4 c5))))
        :set-map '((1 (1 1 1)))
        :rthm-seq-palette '((1 ((((4 4) h (q) e (s) s))
                                :pitch-seq-palette ((1 2 3)))))
        :rthm-seq-map '((1 ((cl (1 1 1))
                            (hn (1 1 1))
                            (vc (1 1 1))))))))
  (next-event mini 'vc nil t)
  (loop for ne = (next-event mini 'vc t nil 2)
     while ne
  collect (bar-num ne)))
******* section (1)
Getting notes for CL
Getting notes for HN
Getting notes for VC
WARNING:
   slippery-chicken::tempo-curve-to-map: No tempo-map or tempo-curve given. 
Using default of crotchet/quarter = 60.
Shortening short, fast leaps...
Shortened 0 large fast leaps
(1 1 1 2 2 2)
SC> (let ((mini
       (make-slippery-chicken
        '+mini+
        :ensemble '(((cl (b-flat-clarinet :midi-channel 1))
                     (hn (french-horn :midi-channel 2))
                     (vc (cello :midi-channel 3))))
        :set-palette '((1 ((f3 g3 a3 b3 c4 d4 e4 f4 g4 a4 b4 c5))))
        :set-map '((1 (1 1 1)))
        :rthm-seq-palette '((1 ((((4 4) h (q) e (s) s))
                                :pitch-seq-palette ((1 2 3)))))
        :rthm-seq-map '((1 ((cl (1 1 1))
                            (hn (1 1 1))
                            (vc (1 1 1))))))))
  (next-event mini 'vc nil t)
  (loop for ne = (next-event mini 'vc t)
     while ne
  collect (bar-num ne)))
******* section (1)
Getting notes for CL
Getting notes for HN
Getting notes for VC
WARNING:
   slippery-chicken::tempo-curve-to-map: No tempo-map or tempo-curve given. 
Using default of crotchet/quarter = 60.
Shortening short, fast leaps...
Shortened 0 large fast leaps
(1 1 1 2 2 2 3 3 3)
SC>

**Comment by danieljamesross** [comment]
Oh I see, THAT's where the end-bar" arg goes. I might tweak the documentation to make it more explicit for idiots like me. I'll try and come up with an RT too, yes.
