### ISSUE TITLE
This returns T for me

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#14]
https://github.com/mdedwards/slippery-chicken/blob/df37970bf1a6ff38debc8cbd274a7a1202763739/pitch.lsp#L679

`(let ((p1 (make-pitch 'C4))
      (p2 (make-pitch 261.63)))
  (pitch= p1 p2))
=>T`

**Comment by mdedwards** [comment]
That's what I would expect. You?

**Comment by danieljamesross** [comment]
Good, that is what I expect. It's just a mistake in the doc then (says it
returns NIL). Excellent. Will change and push.




*Daniel James Ross*
vitruviandan.wordpress.com

**Comment by mdedwards** [comment]
Oh, that's what you're getting at. I couldn't know, you're so mysterious and pithy ;) Anyway, thanks, but it's far too early for you to be at your desk. How dare you be so on the ball at this hour.
