### ISSUE TITLE
Forte's PCS as a chord method

### ISSUE THREAD

**Issue by JRSV** [mdedwards/slippery-chicken#15]
I opened this ticket to discuss the implementation of Forte's Pitch Class Set theory in Slippery Chicken. At first glance, it seems to me that it can be added as a method inside the chord class, however, I wanted to ask if this was the best approach or should I develop a completely new class that accepts a chord object?
(how do you add an "enhancement" label to this issue on github?)

thoughts?

**Comment by mdedwards** [comment]
Seems to me it would be useful to create a subclass of chord that deals with the specificities of PCS theory...

**Comment by JRSV** [comment]
Great!! will look into that. thanks Michael. Will continue this thread if I need more pointers, with some real progress of course.

**Comment by mdedwards** [comment]
ok feel free to open this again if you need help
