### ISSUE TITLE
pitch-or-chord=

### ISSUE THREAD

**Issue by mdedwards** [mdedwards/slippery-chicken#17]
error messages should conform to 

(error "~class::%pitch-or-chord=: p1 is not a pitch or chord: ~a" p1)))

this should be a function not a method as there are no class qualifiers to any of the args

p1 and/or p2 should be allowed to be NIL, in which case NIL would be returned

also the case where a chord object containing only one pitch, this being the same pitch as a pitch object argument, should return something sensible like 'single-pitch-chord=

**Comment by danieljamesross** [comment]
OK, my thinking here was that it should be a method so it returns something useful. But, yes, you are correct, I don't do the testing here. Is there a way for a method to test for several different types in a call? Ideally you would be able to use this method with an event, pitch, or chord object. Maybe we use multiple instances of this method? Is that the way?

**Comment by mdedwards** [comment]
Hi Dan, my email replies don't seem to be getting through here. Here's my response from 14/10:

This is a perfect example for OOP in Lisp:

define the main method for pitch object(s)

then define the method for chord(s), merely passing their pitch(es) to the pitch method of the same name

then another method for event, which calls again the same method with its pitch-or-chord slot, which calls the appropriate method just defined.

Best, Michael

**Comment by danieljamesross** [comment]
OK, perhaps it is better to go for a function then, I'd be repeating functions otherwise.

Why would we want to let p1 = nil pass? Is the error message not more useful?

**Comment by mdedwards** [comment]
in general an error is not so great when you're testing for equality, rather a NIL as a result...with perhaps a warning at the most.

If I've understood you correctly this is definitely a case for methods (as described above) but perhaps an overall function which allows NIL arguments but which then calls -aux methods as described

**Comment by danieljamesross** [comment]
OK, done. There are now methods for pitches, chords and events. Aux method in slippery-chicken.lsp. Also added single-pitch-chord= method.
