### ISSUE TITLE
Bug in midi-play

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#20]
When multiple sections are created using `bars-to-sc`, `midi-play` will only render the first section and ignore the rest.

```lisp
(let* ((ev-list (loop repeat 4 collect (make-event 'a4 'q)))
	   (ev-list2 (loop repeat 4 collect (make-event 'c5 'q)))
	   (bar (make-rthm-seq-bar '((4 4))))
	   (bar2 (make-rthm-seq-bar '((4 4)))))
  (fill-with-rhythms bar ev-list)
  (fill-with-rhythms bar2 ev-list2)
  (bars-to-sc (loop repeat 4 collect bar))
  (bars-to-sc (loop repeat 4 collect bar2) :sc *auto* :section-id 2)
  (midi-play *auto*))
```

**Comment by mdedwards** [comment]
You've opened a huge can of stinky worms here Dan. Allowing the creation of arbitrary new sections means the old methods that gathered data for rendering can no longer rely on simple methods like map references. I think I've fixed this but can't be sure for all other methods. Maybe you can try rendering other score/sound/thingy files from this and similar structures? In any case get latest source and poke to your heart's content. (The main fix is in get-section-refs. The UTs pass for me.)

**Comment by danieljamesross** [comment]
Bloody hell, was worried that might be the case. Thanks for your time and effort!

Have just run the UTs and everything's hunky-dory. The above code works too.

**Comment by mdedwards** [comment]
OK, you're welcome. Thanks for your improvements too.

**Comment by mdedwards** [comment]
BTW I'm adding this code to the UTs now.
