### ISSUE TITLE
No code for method

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#21]
https://github.com/mdedwards/slippery-chicken/blob/89d33b581390cc0c0336066df21745d701428323/slippery-chicken.lsp#L3127

An empty method.

**Comment by mdedwards** [comment]
That's just a placeholder for now. It's doing no harm so let's leave as is.

**Comment by danieljamesross** [comment]
Cool, just wanted to flag it in case it had been forgotten.
