### ISSUE TITLE
Name clash with method in chord.lsp

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#22]
https://github.com/mdedwards/slippery-chicken/blob/3d1f0468845ea1c4530ac43024fd9c7a5ed65921/get-spectrum.lsp#L162

I know it's a different package, but shall we change the name of this for clarity?

Say `(get-spectrum-of-file)` ?

**Comment by mdedwards** [comment]
Hmm, I can see why you'd do that, but there's something about having the same name that makes it like a generic function, even if it's not in this case. I'd keep the name unless it's causing you some bother (?)

**Comment by danieljamesross** [comment]
No, not causing real bother. Just doesn't feel right as it's not a generic function.

**Comment by mdedwards** [comment]
ooh, you're getting fussy aren't you? :)

**Comment by danieljamesross** [comment]
Learned from the best!




*Daniel James Ross*
vitruviandan.wordpress.com

**Comment by mdedwards** [comment]
Hah! I don't know how to respond to that!
