### ISSUE TITLE
Overfull bars in fill-with-rhythms

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#24]
https://github.com/mdedwards/slippery-chicken/blob/4cd3ea62f66aea7ab1af33670a37357545877fca/rthm-seq-bar.lsp#L417

I think I've found a weird bug. The following returns T for me.

```lisp
(let* ((ev-list (loop repeat 5 collect (make-event 'a4 'q)))
	   (bar (make-rthm-seq-bar '((4 4)))))
      (fill-with-rhythms bar ev-list :is-full-error nil :warn nil)
      (is-full bar nil t))
```

**Comment by danieljamesross** [comment]
TBH this might not be a problem with 'fill-with-rhythms' because this also returns T:

```lisp
(let* ((bar (make-rthm-seq-bar
		 '((4 4) q q q q))))
      (add-half-beat-rest bar)
      (is-full bar nil t))
```

**Comment by danieljamesross** [comment]
A-ha, there is no test for `is-full` in the UTs. I will try and have a poke later...

**Comment by danieljamesross** [comment]
UPDATE: 

`add-half-beat-rest` does something with `all-time-sigs`. This is a feature rather than a bug.

The following returns nil as expected:

```lisp
(let* ((bar (make-rthm-seq-bar '((4 4) q q q q))))
      (push (make-event 'a4 'e) (rhythms bar))
      (is-full bar nil t))
```

So the problem, as I see it, is to do with l.599. The `pop` is too simple for this case.

**Comment by danieljamesross** [comment]
Perhaps the answer is to not do anything and just trigger the error in `is-full`?

I have tried this and it def mucks up the unit tests as there are examples of other methods using `fill-with-rhythms`. Hmmmm, rabbit hole.

**Comment by danieljamesross** [comment]
I'm guessing that the `fill-with-rhythms` was originally designed to work with various `chop` methods, right? That would explain why it just knocks the last rhythm off the end with `pop`. I think we need to get creative because users (i.e. me) are using `fill-with-rhythms` in other ways.

So, instead of that `multiple-value-bind` bit from ll.594-600 oughtn't we call a new method?

**Comment by mdedwards** [comment]
```
(let* ((ev-list (loop repeat 5 collect (make-event 'a4 'q)))
	   (bar (make-rthm-seq-bar '((4 4)))))
      (fill-with-rhythms bar ev-list :is-full-error nil :warn nil)
      (is-full bar nil t))
```

why shouldn't that return T? you've provided enough crotchets to fill a bar...

**Comment by mdedwards** [comment]
``(let*` ((bar (make-rthm-seq-bar
		 '((4 4) q q q q))))
      (add-half-beat-rest bar)
      (is-full bar nil t))``

that's also correct, why shouldn' it be full (see doc)?

**Comment by mdedwards** [comment]
> fill-with-rhythms was originally designed to work with various chop

actually no, it was designed to be used similarly to how you're using it here

**Comment by mdedwards** [comment]
> So the problem, as I see it, is to do with l.599. The pop is too simple for this case.

I've yet to see the problem and l.599 in which file???

I'm genuinely confused

**Comment by mdedwards** [comment]
I suppose there could be  a UT for is-full but as there  are several for fill-with-rhythms that check its results (and that method calls is-full) it's being tested implicitly

**Comment by danieljamesross** [comment]
The full story is that I'm generating material en masse and using `fill-with-rhythms`. I then call `orchestrate`. When `:auto-beam t` with the latter, I always get an error.

I thought that `fill-with-rhythms` was somehow allowing overfill bars. I'm struggling to replicate coz it's only happening when I generate a lot of material.

**Comment by mdedwards** [comment]
If you can replicate it would be good to see that Dan. fill-with-rhythms should not be able to overfill a bar if :is-full-error is left at T

I suspect the auto-beam method you're implicitly calling. That's not a foolproof method, I'm afraid. Can you live without it or do we need to go hunting to problem cases?

Best, Michael
