### ISSUE TITLE
no system-open-file on linux

### ISSUE THREAD

**Issue by simonbahr** [mdedwards/slippery-chicken#25]
On mac os, a new output-file (pdf, postscript...) opens automatically after it has been generated. This feature is not yet present on linux, but would be nice to have and easy to add. ;)

The linux-equivalent to osx' "open" is "xdg-open".

The global var *features* on my ubuntu system contains the following list:

(:SLIPPERY-CHICKEN :CM-2 :CM :CMN :ALSA :CLM :CLM5 :CLM4 :CLM3 :CLM2 :SWANK
 :QUICKLISP :SB-BSD-SOCKETS-ADDRINFO :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2
 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :64-BIT :64-BIT-REGISTERS
 :ALIEN-CALLBACKS :ANSI-CL :ASH-RIGHT-VOPS :C-STACK-IS-CONTROL-STACK
 :CALL-SYMBOL :COMMON-LISP :COMPACT-INSTANCE-HEADER :COMPARE-AND-SWAP-VOPS
 :COMPLEX-FLOAT-VOPS :CYCLE-COUNTER :ELF :FLOAT-EQL-VOPS
 :FP-AND-PC-STANDARD-SAVE :GCC-TLS :GENCGC :IEEE-FLOATING-POINT :IMMOBILE-CODE
 :IMMOBILE-SPACE :INLINE-CONSTANTS :INTEGER-EQL-VOP :LARGEFILE :LINKAGE-TABLE
 :LINUX :LITTLE-ENDIAN :MEMORY-BARRIER-VOPS :MULTIPLY-HIGH-VOPS
 :OS-PROVIDES-BLKSIZE-T :OS-PROVIDES-DLADDR :OS-PROVIDES-DLOPEN
 :OS-PROVIDES-GETPROTOBY-R :OS-PROVIDES-POLL :OS-PROVIDES-PUTWC
 :OS-PROVIDES-SUSECONDS-T :PACKAGE-LOCAL-NICKNAMES :RAW-INSTANCE-INIT-VOPS
 :RAW-SIGNED-WORD :RELOCATABLE-HEAP :SB-AFTER-XC-CORE :SB-CORE-COMPRESSION
 :SB-DOC :SB-EVAL :SB-FUTEX :SB-LDB :SB-PACKAGE-LOCKS :SB-SIMD-PACK
 :SB-SOURCE-LOCATIONS :SB-THREAD :SB-UNICODE :SB-XREF-FOR-INTERNALS :SBCL
 :STACK-ALLOCATABLE-CLOSURES :STACK-ALLOCATABLE-FIXED-OBJECTS
 :STACK-ALLOCATABLE-LISTS :STACK-ALLOCATABLE-VECTORS
 :STACK-GROWS-DOWNWARD-NOT-UPWARD :SYMBOL-INFO-VOPS :UNBIND-N-VOP
 :UNDEFINED-FUN-RESTARTS :UNIX :UNWIND-TO-FRAME-AND-CALL-VOP :X86-64)

Is there any element we can use like #+darwin / #-darwin on osx? I guess :LINUX could be the right choice...

**Comment by mdedwards** [comment]
Hi Simon, is xdg-open linux-wide or just part of one distribution?

Also, what's the full path to xdg-open on your (and preferably all) system?

Best, Michael

**Comment by simonbahr** [comment]
Hi Michael,

xdg-open is part of xdg-utils, which should according to freedesktop.org "generally come as part of the operating system". They still "recommend that you package the scripts that your application needs along with your product as a fallback". (https://freedesktop.org/wiki/Software/xdg-utils/)

It is a shellscript that can be downloaded as part of the entire software package from freedesktop.org. I attach the recent version below (as .txt, otherwise it wont upload...)

[xdg-open.txt](https://github.com/mdedwards/slippery-chicken/files/4098694/xdg-open.txt)

In my case, the full path is /usr/bin/xdg-open, but I don't know how reliable that is.

**Comment by simonbahr** [comment]
...The script also includes darwin's "open" – it should work on osx as well, I guess.

`open_darwin()
{
    open "$1"
    if [ $? -eq 0 ]; then
        exit_success
    else
        exit_failure_operation_failed
    fi
}
`

**Comment by mdedwards** [comment]
I've added support for xdg-open in system-open-file (utilities.lsp). I won't package shell scripts with SC simply because that causes all kinds of problems. I'll leave it to the user to make sure it's installed on their system. OK?

**Comment by simonbahr** [comment]
There is still a little issue: The code works, but is not called automatically when calling lp-display.

:lp-display-auto-open should be set to t. It works when I do it by hand.

I think, :sc-auto-open should be pushed into *features* on linux as well. L91 in all.lsp still only does it for darwin:

`#+(and (or sbcl ccl) darwin)
(pushnew :sc-auto-open *features*)
`

But still :lp-display-auto-open is not t when loading sc. It is strange: :sc-auto-open appears in the features list when changing the above code to:

`#+(and (or sbcl ccl) (or darwin linux))
(pushnew :sc-auto-open *features*)
`

But still, :lp-display-auto-open is nil, although it is initialised like this:

`(lp-display-auto-open #+sc-auto-open T #-sc-auto-open nil)`

**Comment by mdedwards** [comment]
well, spotted, yes, that's right. I've updated the src to do this

perhaps you need to delete all the .fasl files in the bin directory and recompile all source files?

as you're finding problems yourself it might be time to add you as a developer so you can check things in as you make improvements, esp. for linux

**Comment by danieljamesross** [comment]
Did someone say remove .fasl files?

```lisp
(in-package :sc)
(require 'uiop)

(defun rm-fasl-files (&key (sc-bin (directory
				    (concatenate 'string 
						   cl-user::+slippery-chicken-src-path+
						   "bin/*.fasl")))
			(cmn-bin (directory #P"~/lisp/cmn/*.fasl"))
			(clm-bin (directory #P"~/lisp/clm-5/*.fasl")))
  "Remove .fasl files from slippery chicken, CMN and CLM-5 folders"
  (let ((ok '()))
    (loop for dir in (list sc-bin cmn-bin clm-bin)
       for count from 1 do
	 (loop for file in dir do
	      (delete-file file))
	 (push count ok))
    (reverse ok)))
```

**Comment by mdedwards** [comment]
ooh errr madam

**Comment by danieljamesross** [comment]
It's not ready for the wider world yet I suppose, but it does save me actual seconds.

**Comment by danieljamesross** [comment]
Full file here:

```lisp
(in-package :sc)
(require 'uiop)

(defun rm-fasl-files (&key
			(sc-bin (directory
				    (concatenate 'string 
						 cl-user::+slippery-chicken-src-path+
						 "bin/*.fasl")))
			(cmn-bin (directory #P"~/lisp/cmn/*.fasl"))
			(clm-bin (directory #P"~/lisp/clm-5/*.fasl")))
  "Remove .fasl files from slippery chicken, CMN and CLM-5 folders"
  (let ((ok '()))
    (loop for dir in (list sc-bin cmn-bin clm-bin)
       for count from 1 do
	 (loop for file in dir do
	      (delete-file file))
	 (push count ok))
    (reverse ok)))

(defun brew-install-sbcl ()
  "Install SBCL to latest version"
  (format t "Initialising...")
  (uiop:run-program "brew upgrade sbcl" :output :string))

(defun sc-rebuild (&key (sc-bin (directory #P"~/sc/bin/*.fasl"))
		     (cmn-bin (directory #P"~/lisp/cmn/*.fasl"))
		     (clm-bin (directory #P"~/lisp/clm-5/*.fasl")))
  (brew-install-sbcl)
  (rm-fasl-files :sc-bin sc-bin :cmn-bin cmn-bin :clm-bin clm-bin))
```

**Comment by mdedwards** [comment]
Thanks Dan!

**Comment by simonbahr** [comment]
Now it works! Thanks!
