### ISSUE TITLE
osc-support on linux

### ISSUE THREAD

**Issue by simonbahr** [mdedwards/slippery-chicken#26]
Hi again, Michael!

As discussed today, it would be great to have OSC support on Linux, too.

Also, I discovered that (osc-call) is not defined when loading slippery-chicken. Is it an active feature, anyway?

**Comment by mdedwards** [comment]
Yes, we should do that Simon.

in all.lisp the following lines only load the respective files on OSX so you won't see the related functions at all in SC on other OSs:

#+(and darwin sbcl) (sc-compile-and-load "osc.lsp")
#+(and darwin sbcl) (sc-compile-and-load "osc-sc.lsp")

I fear we'll need a lot of input from you on this (with your Linux system). We'll definitely need to expand osc-sc.lsp to include Linux and that will mean seeing if we can get the (in-package :sb-bsd-sockets) stuff working. Is that a package on your system? If so, there might actually be very little to do. You could try loading those two files above by hand and see what happens.

Best, Michael

**Comment by simonbahr** [comment]
OK, I tried it out: Both files compile and load, no problems. The package :sb-bsd-sockets exists as well. I can also send data from pd (connect 127.0.0.1 8090 -> mrpeach/udpsend, send 1 -> mrpeach/udpsend). Since 1 is a legal lisp expression, I would expect it to evaluate to 1. But an error occurs:

`osc-sc::osc-call: Couldn't decode buffer: #(1 0 0 0 0 0 0 0 0 0
                                            0 0 0 0 0 0 0 0 0 0 [LOTS OF ZEROS...])
   [Condition of type SIMPLE-ERROR]
`
I also tried sending more "complex" expressions like (+ 1 1), similar error.

Is this a compatibility-issue or am I doing something wrong?

Best, Simon

**Comment by simonbahr** [comment]
OK, a little messy, but I guess I got it. It needs list to symbol conversion and back on the pd side and objects from "mrpeach" and "zexy" libraries. (not very "zexy", but it works...)

![screenshot](https://user-images.githubusercontent.com/60154511/73023576-bd5d3080-3e23-11ea-8f45-3e1ee9b7ceab.png)
(proof: the fibonacci transition is printed in the main pd-window)

The good news: The problems were not about Linux, so no real changes to sc are necessary, except loading "osc.lsp" and "osc-sc.lsp" when loading sc on Linux, too.

The pd-abstraction: 

`#N canvas 1029 120 591 357 10;
#X msg 223 97 connect 127.0.0.1 8090;
#X obj 13 127 mrpeach/udpsend;
#X obj 12 156 mrpeach/udpreceive 8091;
#X obj 13 102 mrpeach/packOSC;
#X obj 12 180 mrpeach/unpackOSC;
#X obj 94 11 loadbang;
#X obj 94 34 f \$0;
#X obj 12 11 inlet;
#X obj 223 73 loadbang;
#X obj 12 316 outlet;
#X obj 13 54 pack s f;
#X obj 13 32 list2symbol;
#X obj 233 254 loadbang;
#X obj 233 277 f \$0;
#X obj 12 293 route osc;
#X msg 234 299 symbol OSC-SC-EVAL-\$1;
#X msg 13 77 send (/osc-sc osc-sc-eval-\$2 \$1);
#X obj 12 224 symbol2list;
#X obj 12 202 symbol;
#X obj 12 246 route list /OSC-SC;
#X obj 12 269 route /OSC-SC;
#X connect 0 0 1 0;
#X connect 2 0 4 0;
#X connect 3 0 1 0;
#X connect 4 0 18 0;
#X connect 5 0 6 0;
#X connect 6 0 10 1;
#X connect 7 0 11 0;
#X connect 8 0 0 0;
#X connect 10 0 16 0;
#X connect 11 0 10 0;
#X connect 12 0 13 0;
#X connect 13 0 15 0;
#X connect 14 0 9 0;
#X connect 15 0 14 1;
#X connect 16 0 3 0;
#X connect 17 0 19 0;
#X connect 18 0 17 0;
#X connect 19 0 20 0;
#X connect 20 0 14 0;
`

Good night, 
Simon

**Comment by mdedwards** [comment]
Interesting, thanks Simon. So PD needs the max equivalents of fromsymbol (as in osc-sc-eval.maxpat) but also something similar when sending. Shame that external packages are needed.

I've added the code to have the two osc files loaded on linux sbcl systems so if you get the latest from the michael branch you should give it a whirl.

Best, Michael

**Comment by mdedwards** [comment]
I've also added your test patch to the documentation examples. This will roll out with the next release.

**Comment by JRSV** [comment]
"Shame that external packages are needed."

hey Michael, no need for externals now. here is the link to some abstractions, but pd vanilla nonetheless. [(https://github.com/gllmAR/pd-osc)]

**Comment by mdedwards** [comment]
Thanks Rafael. Are you suggesting we re-create osc-sc-eval.pd to use something in that package? Best, Michael

**Comment by JRSV** [comment]
> Thanks Rafael. Are you suggesting we re-create osc-sc-eval.pd to use something in that package? Best, Michael

now that I am back in town I will see to this. :)
