### ISSUE TITLE
midi file timing issue

### ISSUE THREAD

**Issue by timpauli** [mdedwards/slippery-chicken#31]
Hi again,

when I run the following code snippet:

````
(in-package :sc)

(defvar events1
    (list 
        (make-event 
            (make-pitch 440) 1 :duration t)))

(events-update-time events1 :start-time 0)

(defvar events2 
    (list 
        (make-event 
            (make-pitch 880) 3 :duration t) 
        (make-event 
            (make-pitch 440) 1 :duration t)))

(events-update-time events2 :start-time 1)


(event-list-to-midi-file 
    (append events1 events2) :midi-file "bug.mid" :auto-open Nil)
````

I would expect to get a midi file with 440hz for 1 pulse, then 880hz for 3 pulses, then 440 hz for 1 pulse. But I get a midi file where the second 440hz start 1 pulse too early, while the 880hz are still playing.

Am I doing something wrong or is there a bug somehow in `events-update-time` or `event-list-to-midi-file`?

When you look at `start-time` and `end-time` values of the events before creating the midi-file, they look correct:

```
(0 1.0) 
(1 4.0) 
(4.0 5.0)
```

Thanks a lot
Best
Tim

**Comment by mdedwards** [comment]
by pulse do you mean beat or seconds?

you've called events-update-time separately with different start-times, which is what you want, right?

when you call make-event with :duration t then you're giving the duration in seconds. That still gets converted to (the nearest) rhythm, with a default tempo of 60. Your MIDI file's default tempo however is, as usual, 120, so you'd need to call event-list-to-midi-file with :start-tempo 60 to get consistent results.

**Comment by timpauli** [comment]
I intentionally used the word pulse because the unit does not matter here for me. 
The example above is made up, just to illustrate the problem, that events end up simultaneous which should appear one after another.
Yes, the 2 calls are intentionally. In my real code I use it to connect bigger parts into one midi file. It makes more sene when you have multiple voices which should happen simultaneously (which is in the minimal bug example above not the case).

Can you reproduce the outcome? Is it clear what I am talking about?

Thx
Tim

**Comment by mdedwards** [comment]
OK, this was in fact a bug in events-update-time: start-time-qtrs default of 0.0 was overriding start-time of 1.0; now it's dependent if start-time-qtrs isn't explicitly given. Technically it was a feature, in that you could have different start-times for MIDI and other files, but in fact it didn't make sense to have :start-time-qtrs ignore :start-time so I've change the default of :start-time-qtrs to be NIL and in that case it will be calculated from the given :start-time and :tempo args.
