### ISSUE TITLE
auto-freq

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#32]
When methods like `make-sfp-from-folder` use `:auto-freq t`, sometimes audio files in the palette have their frequency slot set to zero. This can cause `DIVISION-BY-ZERO` errors during calls to `clm-play` with `:do-src t`.

Might it be a good idea to catch these and default them to, say, 1Hz?

**Comment by mdedwards** [comment]
interesting. i've not seen auto-correlation return 0.0 yet. haven't gone looking for it either. in any case, good catch. i've put in a safety clause to set freq to 'c4 (default at the class level) if frequency detection returns 0 or close to it.

i don't have  a test sndfile for this though so maybe you can give it a poke?

**Comment by danieljamesross** [comment]
l. 327 of sndfile.lsp causses a load error because `equal-within-less-tolerance` is defined in the tests but not sc proper.

**Comment by danieljamesross** [comment]
I changed the line and committed. All works now, thanks.

**Comment by mdedwards** [comment]
ah we both did the same thing :) yes, equal-within-tolerance was what i intended...my auto-completion got a bit too enthusiastic

i've merged the changes to resolve the conflict
