### ISSUE TITLE
add-harmonics prints everything and can take ages

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#33]
Can we have an option to turn off printing for add-harmonics? When one has a large set-palette and wants to use the add-harmonics method the printing can take an eternity.

**Comment by mdedwards** [comment]
need a bit more detail Dan. When I use that method on a set it returns T and doesn't print anything unless there are duplicate pitches.

**Comment by danieljamesross** [comment]
It must be the duplicate pitches. I'm doing some auto-generation of material, retro-actively generating a set-palette, stuffing it with extra harmonics just in case, all so I can use things like `shorten-large-fast-leaps` which rely on palettes. There are no doubt many duplicate pitches. Would you know off the top of your head where the code is that prints all the pitches when it finds and removes them?

**Comment by mdedwards** [comment]
That'll be in the init-instance of sc-set I think.

Why don't use just remove duplicate pitches yourself or at least when creating a set set the :warn-dups slot to NIL. It was made for that after all

**Comment by danieljamesross** [comment]
nice one, thanks!
