### ISSUE TITLE
access pitch-seq-palettes of rthm-seq-palette

### ISSUE THREAD

**Issue by timpauli** [mdedwards/slippery-chicken#34]
Hello,

I used `make-rthm-chain` to create a `rthm-seq-palette`. Now I want to insert my own `pitch-seq-palette` into the `rthm-seqs`. Is there a simpler way than `(pitch-seq-palette (first (data (data (first (data (palette +rthm-chain+)))))))` to access the `pitch-seq-palette?

Thank you.
Tim

**Comment by danieljamesross** [comment]
Take a look at the `create-psps` method.

Some info here: [https://michael-edwards.org/sc/manual/rhythm-chains.html#example](https://michael-edwards.org/sc/manual/rhythm-chains.html#example)

**Comment by mdedwards** [comment]
Dan's right: that's the main method I've always used but the assoc-list / recursive-assoc-list methods get-data and get-all-refs are also your friends here. I found one issue with the following code fixed by relink-named-objects so update your git source from the michael branch and this will work nicely for you. In any case all those first and data calls are nasty. Not a way I'd like to go. 

```
(let* ((rch
          (make-rthm-chain
           'test-rch 100
           '((((e) e) ; 4 in total
              (- s (s) (s) s -)
              ({ 3 (te) - te te - })
              ((e.) s))
             (({ 3 (te) te (te) }) ; what we transition to
              ({ 3 - te (te) te - })
              ({ 3 (te) - te te - })
              ({ 3 (te) (te) te })))
           '((((q q) ; the 2/4 bars: 5 total
               ((q) q)
               ((q) q)
               ((q) (s) e.)
               (- e e - (e) e))
              (({ 3 te+te te+te te+te }) ; what we transition to
               (q - s e. -)
               (q (s) e.)
               (q (s) - s e -)
               ({ 3 te+te te+te - te te - })))
             ((((e.) s (e) e (s) e.) ; the 3/4 bars: 4 total
               (- e e - (e) e (q))
               (- e. s - - +e e - (q))
               (q (e.) s (q)))
              (({ 3 (te) (te) te+te te+te } (q)) ; what we transition to
               (- e. s - (q) (s) - s e -)
               ({ 3 te+te te } (q) q)
               ({ 3 - te te te - } (e) e { 3 (te) (te) te }))))
           :players '(fl cl))))
  (loop for ref in (get-all-refs (palette rch)) do
       (print (pitch-seq-palette (get-data ref (palette rch))))))
```

Let us know how you get on.
