### ISSUE TITLE
list-member

### ISSUE THREAD

**Issue by mdedwards** [mdedwards/slippery-chicken#35]
Hello Dan, I've just seen your list-member function. Besides your warnings what's the difference between this and the ANSI lisp function intersection?

**Comment by danieljamesross** [comment]
The difference is: I didn't know `intersection` existed until just now.

**Comment by danieljamesross** [comment]
...and it's also way less efficient

**Comment by mdedwards** [comment]
Yikes!

Will you update/remove ( you might like the warnings)? If so please pull the latest changes from today

**Comment by danieljamesross** [comment]
I'll remove it later

**Comment by mdedwards** [comment]
I sympathise: Lisp is huge and I still don't know the half of it, because I don't need the half of it, but with functions where you think "surely that exists already", they usually do

**Comment by danieljamesross** [comment]
Indeed, just wouldn't have thought about calling it "intersection".

**Comment by danieljamesross** [comment]
Removed
