### ISSUE TITLE
Update installation WIKI

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#38]
How would you feel if I were to update the installation [wiki](https://github.com/mdedwards/slippery-chicken/wiki/how-to-install-slippery-chicken-'by-hand') to include the wildcard entry I have? It means that every time I update SBCL, I don't have to go and change my .emacs. Saves crucial seconds!

```lisp
(let ((sbcl-local (car (file-expand-wildcards
			"/usr/local/Cellar/sbcl/*/lib/sbcl/sbcl.core"))))
  (setq slime-lisp-implementations
	`((sbcl ("/usr/local/bin/sbcl"
		 "--core"
		 ;; replace with correct path of sbcl
		 ,sbcl-local
		 "--dynamic-space-size" "2147")))))
```

**Comment by mdedwards** [comment]
Not sure why some email replies arrive here, and some don't. This from the 28th May: 

OK, why not? If that works for everyone, then why not? Thanks!

**Comment by danieljamesross** [comment]
Updated. 

As well as changing this, I've been updating some of the code examples to show lisp (syntax highlighting)[https://guides.github.com/features/mastering-markdown/].

**Comment by mdedwards** [comment]
Nice, thanks Dan!
