### ISSUE TITLE
old stuff; could have used pathname functions for this....

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#39]
> old stuff; could have used pathname functions for this....

Indeed we can, 

```lisp
(uiop:pathname-parent-directory-pathname
```

https://github.com/mdedwards/slippery-chicken/blob/3d1f0468845ea1c4530ac43024fd9c7a5ed65921/all.lsp#L106

**Comment by mdedwards** [comment]
Quite true, but as this works and is ANSI Lisp there's no reason to change it, right? UIOP and ASDF are not ANSI...

**Comment by danieljamesross** [comment]
I suppose not. I've been getting into UIOP a lot recently and love it.
