### ISSUE TITLE
Incorrect tempo for bpm < 4=q in midi file

### ISSUE THREAD

**Issue by uummoo** [mdedwards/slippery-chicken#5]
Hello Michael,

somehow slippery chickens midi-play method can't handle tempo values for bpm < 4 q.

For instance:
q = 2 leads to q = 5
q = 3 leads to q = 19
etc.

#### minimal example:
```commonlisp
(load "src/all.lsp")
(in-package :sc)

(let* ((mini
       (make-slippery-chicken
        '+mini+
        :ensemble '(((vn (violin :midi-channel 1))))
        :set-palette '((1 ((c4 e4 g4))))
        :set-map '((1 (1)))
        :rthm-seq-palette '((1 ((((2 4) q e e))
                                :pitch-seq-palette ((1 2 3)))))
        :rthm-seq-map '((1 ((vn (1)))))
	:tempo-map '((1 (q 2))))))
  (midi-play mini :midi-file "midi/tempo-test.mid")
  (write-lp-data-for-all mini :base-path "lilypond"))
```

It seems to be a problem specific to the generation of midi-files, since the corresponding lilypond output represents the tempo correctly. If the problem is unsolvable due to limitations of midi-files, I might suggest adding a warning or error message for bpm values < 4 q?

Best regards,

Levin

**Comment by mdedwards** [comment]
Hallo Levin. Lustig, Tempo 4. Schaue ich am Wochenende an. Grüße aus
Schottland, Michael

**Comment by mdedwards** [comment]
Hi Levin, I can confirm that I'm experiencing the same problems with both Rondo and Reaper as playback software on OSX. BPM 4 is the limit for me too. I haven't checked exhaustively but I can't find reference to a minimum tempo in MIDI files. It's possibly an oversight in the MIDI 1.0 specs. In any case SC now issues a warning when tempo dips below 4. Can't imagine many people ever seeing that though. One for the freaks, like your good self ;)
