### ISSUE TITLE
Requiring ASDF may be unnecessary

### ISSUE THREAD

**Issue by phoe** [mdedwards/slippery-chicken#52]
https://github.com/mdedwards/slippery-chicken/blob/0658eaccfca468888eab348ae9d0d35bf60a28e9/src/all.lsp#L46-L48

I see that ASDF is not used anywhere else in the source code. AFAIK it is not necessary to require ASDF only to load some of SBCL contribs - it should be possible to directly `require` them instead:

```lisp
#+sbcl (require :sb-bsd-sockets)
#+sbcl (require :sb-posix)
```

**Comment by mdedwards** [comment]
Thanks for this Phoe. I just commented out line 46 and reloaded the system. The following error popped up:

    Package ASDF does not exist.

      Line: 47, Column: 24, File-Position: 1873

      Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /Users/michael/sc/src/all.lsp" {1010FA5333}>

**Comment by phoe** [comment]
This is because you also need to change L47 and L48 to use `require` over `asdf:load-system` in addition to commenting out L46.

**Comment by mdedwards** [comment]
Ah, gotcha, nice, now I understand. Done. Any asdf suggestions gratefully received. We've been planning asdf and quicklisp integration but can't get away from composition/teaching long enough to attack it properly

**Comment by danieljamesross** [comment]
Looks like this issue can now be closed.

**Comment by phoe** [comment]
No, why? The lines that depend on `#+asdf` have not been removed or changed.

https://github.com/mdedwards/slippery-chicken/blob/c1c11fadcdb40cd869d5b29091ba5e53c5270e04/src/all.lsp#L47-L48

**Comment by danieljamesross** [comment]
They have been on the michael branch and will be merged into master on the next release.
