### ISSUE TITLE
slippery-chicken package for GNU Guix

### ISSUE THREAD

**Issue by jgarte** [mdedwards/slippery-chicken#57]
I started packaging slippery-chicken in a branch of a Guix [channel](https://guix.gnu.org/manual/en/html_node/Channels.html) called [Guix 'R Us](https://whereis.みんな/):

https://git.sr.ht/~whereiseveryone/guixrus/tree/slippery-chicken/item/guixrus/packages/slippery-chicken.scm#L36

A Guix package is [scheme](https://en.wikipedia.org/wiki/Scheme_(programming_language)) code written in [GNU Guile](https://www.gnu.org/software/guile/).

In order for a slippery-chicken Guix package to be practical we will need to resolve a few things that are dependent on #44 

One is, we need an ASD file for slippery-chicken.

1. In order to write a ASD file for slippery-chicken we need to know the exact order in which the slippery chicken files are loaded.

It looks like [all.lsp](https://github.com/mdedwards/slippery-chicken/blob/master/src/all.lsp#L207) might have the correct load order.

The ASD example below uses the order in `all.lsp`.

3. Then we need to reflect that in the ASD file, with the `:serial t` option which will load those files in the correct sequence.

From the [ASDF manual](https://asdf.common-lisp.dev/asdf.html):
> 
The :serial t says that each sub-component of mod depends on the previous components, so that cooker.lisp depends-on reader.lisp, which depends-on utils.lisp. Also data.raw depends on all of them, but that doesn’t matter since it’s a static file; on the other hand, if it appeared first, then all the Lisp files would be recompiled when the data is modified, which is probably not what is desired in this case.

 

Here's a starter ASD file assuming that the system will be called `sc`:

```lisp
(asdf:defsystem #:sc
  :description "algorithmic composition software in common lisp and clos"
  :author "Michael Edwards"
  :license  "GPL-3"
  :version "1.0.12"
  :serial t
  :pathname "src"
  :depends-on (#:cmn
                        #:cm)
   ;;  Is this the correct load order for these files?
  :components      ((:file "package")
(:file "cmn") ; cmn
(:file "cmn-glyphs") ; cmn
(:file "cm") ; cm
(:file "cm-cm") ; cm
(:file "samp5") ; clm
(:file "sine") ; clm
(:file "autoc") ; clm
(:file "cm-load" t)
(:file "utilities")
(:file "named-object")
(:file "music-xml")
(:file "linked-named-object")
(:file "sclist")
(:file "circular-sclist")
(:file "assoc-list")
(:file "recursive-assoc-list")
(:file "activity-levels")
(:file "activity-levels-env")
(:file "palette")
(:file "pitch-seq-palette")
(:file "globals")
(:file "sc-map")
(:file "set-map")
(:file "tempo")
(:file "rhythm")
(:file "pitch")
(:file "chord")
(:file "event")
(:file "instrument")
;; (:file "globals")
(:file "time-sig")
(:file "rthm-seq-bar")
(:file "change-data")
(:file "change-map")
(:file "instrument-change-map")
(:file "simple-change-map")
(:file "tempo-map")
(:file "sc-set")
(:file "tl-set")
(:file "complete-set")
(:file "set-palette")
(:file "pitch-seq")
(:file "sndfile")
(:file "sndfile-ext")
(:file "sndfile-palette")
(:file "sndfilenet")
(:file "rthm-seq")
(:file "rthm-seq-palette")
(:file "rthm-seq-map")
(:file "instrument-palette")
(:file "instruments")
(:file "player")
(:file "bar-holder")
(:file "sequenz")
(:file "ensemble")
(:file "l-for-lookup")
(:file "player-section")
(:file "section")
(:file "slippery-chicken")
(:file "piece")
(:file "slippery-chicken-edit")
(:file "clm") ; clm
(:file "permutations")
(:file "rthm-chain")
(:file "rthm-chain-slow")
(:file "cycle-repeats")
(:file "recurring-event")
(:file "intervals-mapper")
(:file "lilypond")
(:file "popcorn")
(:file "osc")
(:file "osc-sc")
(:file "osc-sc-bsd")
(:file "get-spectrum") ; clm
(:file "spectra")
(:file "control-wave") ; clm 
(:file "control-wave-ins") ; clm
(:file "wolfram" t)
(:file "afu")
(:file "reaper"))) ; Can we ignore this file since we'll be packaging for Guix which doesn't package reaper?
```
Excuse the spacing above. GitHub's formatting is a little buggy.

**Comment by mdedwards** [comment]
Hi, the order should be exactly that as found in sc’s all.lsp

with asd you’ll probably run into the problem of sc’s version of common music, which comes with its own asd file, and which is incorporated into sc. THat’s the one essential pre-existing package, as I’ve mentioned elsewhere. CLM and CMN are not essential.

Best, Michael

**Comment by jgarte** [comment]
> THat’s the one essential pre-existing package, as I’ve mentioned elsewhere. CLM and CMN are not essential.

@mdedwards 

Oh, sorry, I see you answered my question regarding `cm` here. Thank you.

My strategy now will be to package `cm` (`common music`) for Guix and then use what Guix calls a `snippet ` to delete the vendored `cm` library after cloning the repository from GitHub and install `slippery-chicken` with the Guix-managed `cm` package.

The snippet will look something like this

```
         (modules '((guix build utils)))
         (snippet
          '(begin
             ;; Remove a bundled common music.
             (delete-file-recursively "src/cm-2.6.0")
             #t))))

```

**Comment by mdedwards** [comment]
Hello there, we've finally made slippery chicken asdf-friendly. If you haven't completely given up you might want to integrate into Guix now. Best, Michael

**Comment by jgarte** [comment]
@mdedwards Thanks for the update. I'm planning to work on the Guix package still. I'll keep you posted on when I try again.

**Comment by jgarte** [comment]
@mdedwards I finally got around to packaging `slippery-chicken` 🎉 

https://codeberg.org/guix/guix/commit/c3a4982ca9a161b39af76fad1b5bdaf6050635e7

**Comment by mdedwards** [comment]
Many thanks!
