### ISSUE TITLE
Change cmn-display standard output to PDF

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#67]
With MacOS 13 (Ventura), Apple drops the support of the EPS format in the preview.app. As this implies that scores generated via `cmn-display` cannot be displayed without preceding format conversion, it might be a good idea to change the default output format of `cmn-display` to PDF.

**Comment by mdedwards** [comment]
Thanks Ruben. Pull the last code then do the following before your call to cmn-display:

(set-sc-config 'autoconvert-eps-to-pdf t)

Best, Michael

**Comment by rubenphilipp** [comment]
Marvelous. Thank you, Michael!

Best
Ruben

**Comment by rubenphilipp** [comment]
I guess it is time to say farewell to this issue, isn't it?

**Comment by mdedwards** [comment]
Great to read that it now works for you Ruben. 

Feel free to close if you’re happy.

These parts of SC that I haven’t yet used in a piece will have problems like this. Apologies in advance. It’s a philosophical thing: do you only release software when it’s completely, in all its nooks and crannies, bombenfest, or do you have a few dodgy areas that people like your good self discover and thus poke you into improving. Best, Michael
