### ISSUE TITLE
Bug in write-reaper-file

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#70]
Hello Michael,

I am creating a Reaper file via `write-reaper-file` by passing a list of lists with marker data as `:markers` argument. As my output file did not contain any marker, I have had a look at reaper.lsp and noticed that the `apply` (line 398) does not contain the proper output stream. I will commit a fix in a second, but opened this issue for reference.

Best
Ruben

**Comment by rubenphilipp** [comment]
Hello again,

I've noticed, that my solution is actually preventing the use of the colour argument, as the stream argument precedes the colour argument. As far as I know, it is hardly (if at all) possible to pass the "out" stream via the lists given as `:makers` to `write-reaper-file`–correct me if I am wrong. My solution, which does not require changing the logic of the functions/methods in reaper.lsp, would be to propose a specific marker-sublist-syntax for `write-reaper-file` (i.e. `'(number time label colour)`) which will then be parsed in `make-reaper-file`. 

Best 
Ruben

**Comment by mdedwards** [comment]
Good eyes Ruben!

I’ve found a fix that I think works and added a more robust test also. This is a bit clumsy (write-reaper-file) but I’d rather not change argument order and break logic elsewhere

        (loop for m in markers and i from 1 do
                 (if (numberp m)
                     (write-reaper-marker i m "" out)
                     (let* ((len (length m))
                            (args (if (> len 3)
                                      (append (subseq m 0 3) (list out)
                                              (last m))
                                      (econs m out))))
                       (apply #'write-reaper-marker args)))))

I can’t check in because I think you’ve checked in some failing code—can you roll that back so I can proceed?

Best, Michael

**Comment by rubenphilipp** [comment]
I like reading code… ;)
This looks like a proper solution. Thanks, Michael! Should we add something to the documentation mentioning that the format argument required by `write-reaper-marker` will be omitted but should be included (e.g. as nil) in the lists?

I will take care of removing my last commit. Do you have any preferred method? I would just `git revert` commit 88d5a465afca231fa3d7964cda320747c1715abd. Any other recommendation?

Best
Ruben

**Comment by mdedwards** [comment]
Hi Ruben,

> I like reading code… ;)

Aye but do you print it out and fondle it yet?
> This looks like a proper solution. Thanks, Michael! Should we add something to the documentation mentioning that the format argument required by write-reaper-marker will be omitted but should be included (e.g. as nil) in the lists?
> 
I think it’s covered in the robodoc I wrote for the method. The others will need doc soon too.

> I will take care of removing my last commit. Do you have any preferred method? I would just git revert commit 88d5a46 <https://github.com/mdedwards/slippery-chicken/commit/88d5a465afca231fa3d7964cda320747c1715abd>. Any other recommendation?
> 

Ah don’t worry about it. I’ve just done a manual merge to resolve the conflicts. You can pull and test it yourself now if you like. 

Best, Michael

**Comment by rubenphilipp** [comment]
> Aye but do you print it out and fondle it yet?

I would never leave Emacs.

> I think it’s covered in the robodoc I wrote for the method.

I see. Very diligent!

> You can pull and test it yourself now if you like.

Of course, I do–and did. Works flawlessly. 

Thanks
Ruben
