### ISSUE TITLE
ppcre

### ISSUE THREAD

**Issue by mdedwards** [mdedwards/slippery-chicken#71]
Hello, this one is meant mainly for Leon Focker, who added the ppcre functionality a few days ago. As you know, I'm sceptical about being dependent on packages I have no control over. So, is there a way in your import-ppcre function that you could 'back out gracefully' at any point that the function fails to find things it needs, such as the ppcre package itself here on GitHub? E.g. making sure the clone worked before proceeding with asdf stuff? Could you also add comments to explain why it's necessary etc.? Best, Michael

**Comment by danieljamesross** [comment]
I've said it before, we should really get sc on quicklisp, then all this kinda stuff is handled for us and we integrate nicely with the rest of the common lisp ecosystem. We would also get more users and, hopefully, maintainers too.

**Comment by Leon-Focker** [comment]
Maybe we could start a new branch for that? Only to bridge that initial time of switching and experimenting with quicklisp. Then we can start with ppcre and work up to the trickier stuff like clm... In my experience, once it does work, quicklisp works great for easy installations independant of the system I'm using. It is then also a good way to manage libraries and for them to be installed in the same way/ directory. So I do support the initiative. 

Or maybe, as an alternative - in case quicklisp is not coming to sc any time soon - I could just make a fork or whatever of the ppcre library. Then we do not depend so much on the developers changing something crucial or taking it down.

**Comment by Leon-Focker** [comment]
I might be missing something. But currently common music is literally hardcoded as a part of slippery chickens source code. When switching to quicklisp, it will just be loaded as part of sc. Why would you want to use Orms version, when it is currently working just fine and why is that coupled with the decision for or against quicklisp? In my eyes, it would make more sense to first switch to quicklisp and then think about Orms CM (or do so independantly)...

Common Music Notation and Common Lisp Music could also probably easily be quicklispified, by hosting a fork on Github and including an .asd file. We might not even have to register them with quicklisp (thought it would be cleaner and nicer as soon as we do the same for slippery chicken), slippery chicken could handle the download similar to ppcre now. Or am I wrong?

**Comment by mdedwards** [comment]
> I might be missing something. But currently common music is literally hardcoded as a part of slippery chickens source code. When switching to quicklisp, it will just be loaded as part of sc. Why would you want to use Orms version, when it is currently working just fine and why is that coupled with the decision for or against quicklisp?
> 

Because it’s in reality a separate package, that already exists, and thus would go against the basic idea of quicklisp and other library  managers, to have a separate version within slippery chicken 

> In my eyes, it would make more sense to first switch to quicklisp and then think about Orms CM (or do so independantly)...
> 

Nah, CM first of all, then the rest, IMHO

> Common Music Notation and Common Lisp Music could also probably easily be quicklispified, by hosting a fork on Github and including an .asd file.
> 

As long as Bill Schottstaedt is happy with that...

> We might not even have to register them with quicklisp (thought it would be cleaner and nicer as soon as we do the same for slippery chicken), slippery chicken could handle the download similar to ppcre now. Or am I wrong?
> 
The whole point would be to avoid such a download, no? So keep all the packages separate but dependent on each other.

Cheers, M

**Comment by danieljamesross** [comment]
I agree that is makes sense to add all these libs to quicklisp (providing permissions etc) but think it makes sense to start with `sc` because if it becomes difficult/awkward/impossible to add `sc` to `ql`, then there's no point adding `CM` and `CLM` in the first place. 

In true `sc` style oughtn't we go for a top-down approach? 😉 
![Screenshot 2023-12-07 at 14 19 20](https://github.com/mdedwards/slippery-chicken/assets/28922296/5d606289-9037-4ba7-88a0-03df28da0757)

**Comment by mdedwards** [comment]
And thus begin the difficulties….On 7. Dec 2023, at 15:41, Leon Focker ***@***.***> wrote:﻿
Okay, in case we had to take out the CM code and wanted all libraries to be registered with quicklisp, we also have to convince Orm to register CM. Because as fair as I'm aware, he hasn't done so (at least I cannot find it: https://www.quicklisp.org/beta/releases.html).

**Comment by Leon-Focker** [comment]
I'm closing this for now - see #83 and #81
