### ISSUE TITLE
reaper-play: derive automatic file-path from default-dir

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#73]
Hey Michael,

thanks again for your work on reaper-play. 
Did you have anything specific in mind when deciding that the default path for the rpp-file (when `:file` = NIL) is relative to the CWD of the current CL-instance instead of, for example, to the default-dir (e.g. via `default-dir-file`)? 
I find this slightly confusing, as this differs from common slippery chicken "behavior" and suggest changing the default file-path as described above. 

Best
Ruben

**Comment by mdedwards** [comment]
Hello Ruben, that was just an oversight and something I'd probably had picked up when making my first piece with the method. Feel free to improve but maybe the tests need changing to read from /tmp. Best, Michael

**Comment by rubenphilipp** [comment]
I have fixed this and will push a commit in a moment. The tests did not need to be changed.
