### ISSUE TITLE
music-xml: Implement <harp-pedals> in function xml-salzedo

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#75]
As of now, the `xml-salzedo` function used to create harp pedal marks in `music-xml.lsp` makes use of ordinary text-marks (via `<words>`). The reason for this decision when writing the function was based in the fact that most music notation programs do not support the MusicXML-standard element `<harp-pedals>`.[^1] As this might/will (hopefully) change in the future, it is desirable to either 1) replace the current work-around with the proper MusicXML-markup or 2) provide the user with the decision which method to use (e.g. via `sc-set-config`).

[^1]: https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/harp-pedals/

**Comment by mdedwards** [comment]
Reopening and leaving open as this could be implemented some time in the future.

**Comment by rubenphilipp** [comment]
I already did (cf. 6d5bceaa445d7a4c3667ddb86e7d9356686b243c). ;)

**Comment by mdedwards** [comment]
Oh wow, I thought there was a code moratorium :-)

**Comment by rubenphilipp** [comment]
Indeed, but I thought it was time for a Christmas present. ;)Am 28.12.2023 um 13:58 schrieb Michael Edwards ***@***.***>:﻿
Oh wow, I thought there was a code moratorium :-)

**Comment by mdedwards** [comment]
😅On 29. Dec 2023, at 01:42, Ruben Philipp ***@***.***> wrote:﻿
Indeed, but I thought it was time for a Christmas present. ;)Am 28.12.2023 um 13:58 schrieb Michael Edwards ***@***.***>:﻿

Oh wow, I thought there was a code moratorium :-)
