### ISSUE TITLE
new lines within format strings create compatibility issues between platforms

### ISSUE THREAD

**Issue by Leon-Focker** [mdedwards/slippery-chicken#77]
This is an error message I get when trying to use the write-xml function on Windows:
```
Execution of a form compiled with errors.
Form:
  (FORMATTER "~&<?xml version=\"1.0\" encoding=\"UTF-8\" ~^M

                 standalone=\"no\"?>")
Compile-time error:
  during macroexpansion of
(FORMATTER "~&<?xml version=\"1.0\" encoding=\"UTF-8\" ~^M

                 standalone=\"no\"?>").
Use *BREAK-ON-SIGNALS* to intercept.

 error in FORMAT: Unknown directive (character: Return)
  ~&<?xml version="1.0" encoding="UTF-8" ~^M

                 standalone="no"?>
                                          ^
   [Condition of type SB-INT:COMPILED-PROGRAM-ERROR]
```
It seems like using ~ to prevent overly long lines within a format creates this issue. Should all of those instances be changed or is there another solution?

**Comment by Leon-Focker** [comment]
I think using grep-find in emacs and then:
`find . -type f -exec grep --color -nH --null -e '~$' \{\} +`
should do the trick for finding these. Not sure if there is a good way to do a search and replace within emacs though...

**Comment by Leon-Focker** [comment]
One could do a simple query-replace or string-replace and use C-q C-j to look and replace newlines:
https://stackoverflow.com/questions/6886024/how-to-replace-a-search-with-multiple-lines-in-emacs

**Comment by mdedwards** [comment]
Nice! grep-find is new to me. Very handy, thanks. There are however 1233 matching lines and I don't think any amount of query-replace savagery will do the trick--mainly because the arguments to ~a will have to be shunted around the various new (format ) calls. I fear the only way is by hand :/

However, let's make sure it's worth it first--assuming we don't just say windoze users should just install linux?--I've updated write-xm in the sc class. Please git pull it and see if it now works for you.

**Comment by mdedwards** [comment]
though of course we could do a query-replace simply to create long lines: ugly but would work and then any time we see such a long line we (just me?) groan and fix it with a separate format call

BTW in emacs there's tags-query-replace: used to use it loads way back when

**Comment by danieljamesross** [comment]
This is a known bug in Lisp on Windows. Rather than changing all the code, making `format` lines less readable, can you not get your editor to use Linux-style line endings?

**Comment by mdedwards** [comment]
Is that just SBCL Dan?

I've done the buffer encoding thing a lot myself but it's not something we should expect every SC user to do with every .lsp file: we need to provide usable source code surely?

**Comment by danieljamesross** [comment]
Clozure CL too I think. Yes, perhaps you're correct. There are folx online that reckon these Lisp implementations break unicode guidelines.

**Comment by Leon-Focker** [comment]
Changing my emacs config seems to only work for files that I write. However it made me realise that I hadn't pulled sc for a while on windows (because I don't use the same directory as on linux). In the meantime I switched using to GitBash and also changed my line encodings there. This fixes the problem for me, because I always checkout with LF, not CLRF. 
So changing my emacs config and my git config is kind of a solution - not sure if that's suitable for all users.

> Please git pull it and see if it now works for you.

I pulled and saved again on windows notepad. Seems to work, but aren't there some left in l. 7910?

**Comment by mdedwards** [comment]
As you write, changing emacs won't help until you save the file, which most users won't do, so that's not a solution. But checking out with LF is. What's the git command to do that?

We could just add a warning to people on the main page that windoze users need LF. That would perhaps suffice.

Fixed those on L7910; thanks for that.

**Comment by Leon-Focker** [comment]
Let me try what happens if I do that.

**Comment by Leon-Focker** [comment]
Currently there is not problem with downloading the .zip. This would only be a problem, I think, if files using CLRF within format would be pushed to sc. IDK if there is a way to check/prevent this...

**Comment by mdedwards** [comment]
Me neither, but if I understood you correctly, you downloaded the source as a zip from a windows machine and after compiling it and running e.g. write-xml you had no problems. But what about write-lp-data-for-all, which currently still has format calls with line breaks?

**Comment by Leon-Focker** [comment]
Good point, tried it again and write-lp-data is also fine in that regard. However, there is a problem with the default paths: 
`(get-sc-config 'default-dir)` as that is "/tmp/" which, of course, windows doesn't have :)
If you supply a path, then there is no problem. I think the default-dir problem could be fixed with the os-format-path function. I noticed a few bugs in that one though, so I edited it [(`8f6654c`).](https://github.com/mdedwards/slippery-chicken/commit/8f6654cd3c2391ac28dba971cebc65a97436822a) Should work as expected now.

**Comment by mdedwards** [comment]
OK, I've pulled your corrections and the tests pass fine.

What's the (guaranteed) tmp equivalent in windows?

BTW suddenly I'm getting this when I run git status:

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	src/ppcre/

**Comment by Leon-Focker** [comment]
> BTW suddenly I'm getting this when I run git status:

That's because you changed the .gitignore: [d7ffa1a](https://github.com/mdedwards/slippery-chicken/commit/d7ffa1a80f06ab5b372ee3a20e8320d2dd9d1784)

**Comment by Leon-Focker** [comment]
> What's the (guaranteed) tmp equivalent in windows?

I think "c:/tmp/" should be fine in pretty much any case. But forget what I said about using os-format-path for this. Just using 
```
#+(or win32 win64) "c:/tmp/" 
#-(or win32 win64) "/tmp/" 
```
when setting the default should do the trick, right?

**Comment by mdedwards** [comment]
> > BTW suddenly I'm getting this when I run git status:
> 
> That's because you changed the .gitignore: [d7ffa1a](https://github.com/mdedwards/slippery-chicken/commit/d7ffa1a80f06ab5b372ee3a20e8320d2dd9d1784)

Oh man, it's the day that line breaks will kill you! I did my usual cat >> .gitignore to add a new file and it stuck it onto src/ppcre  --- glad you're awake '-)

**Comment by Leon-Focker** [comment]
Works on Windows, too!

**Comment by mdedwards** [comment]
So would it be true to say that if you download the code as a zip, on a win machine, you get win-style line breaks and the new lines in the format calls are fine; whereas if you change these **on win also I assume**

core.eol=lf
core.autocrlf=false

then do a clone, all hell breaks loose? The implication being, that if you don't change those and do a clone from some sort of shell on win, all should be fine too, i.e. it was the core config stuff that was screwing things up?

**Comment by mdedwards** [comment]
No, I meant something else. From your point of view, how did you hit the error with write-xml, especially given that without the format changes, e.g. write-lp-data-for-all does not trigger a similar error?

**Comment by Leon-Focker** [comment]
Ah. Well the original code was probably using LF and should have worked. However, I had the older version of sc for a while and didn't use git or emacs with correct encoding. I guess it must have converted newlines when opening the file or during whatever process. I don't know. But I would say: As long as the source code is using LF, there is no problem when downloading it. As soon as you're doing something with it on Windows that might change...
