### ISSUE TITLE
sound-duration substitute

### ISSUE THREAD

**Issue by mdedwards** [mdedwards/slippery-chicken#82]
For reaper-play we need the sound's duration, channels, sampling rate: we get these from clm up to now but will need a substitute for people who want reaper-play but not CLM. Use MediaInfo and parse the output (in lisp (pprce?) rather than a shell script).

**Comment by rubenphilipp** [comment]
Maybe [ffprobe](https://wiki.ubuntuusers.de/ffprobe/) could also be an option!?

**Comment by mdedwards** [comment]
@rubenphilipp  Do you see an advance of that over MediaInfo?

@Leon-Focker I've just added the shell-to-string function for sbcl so that we can grab and parse data for reaper-play in the absence of clm. Any chance you could do your pprce regex magic to parse the data for duration, channels, samplrate and bit depth?

`(shell-to-string "/usr/local/bin/MediaInfo" "/Users/michael/Library/Mobile Documents/com~apple~CloudDocs/code/lisp/sc-ql/tests/test-sndfiles-dir-1/test-sndfile-1.aiff")`

`"General
Complete name                            : /Users/michael/Library/Mobile Documents/com~apple~CloudDocs/code/lisp/sc-ql/tests/test-sndfiles-dir-1/test-sndfile-1.aiff
Format                                   : AIFF
Format/Info                              : Apple/SGI
File size                                : 186 KiB
Duration                                 : 2 s 159 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 706 kb/s

Audio
Format                                   : PCM
Format settings                          : Big
Duration                                 : 2 s 159 ms
Bit rate mode                            : Constant
Bit rate                                 : 705.6 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Stream size                              : 186 KiB (100%)


"`

**Comment by Leon-Focker** [comment]
@mdedwards Sure, I'll have a look!

**Comment by Leon-Focker** [comment]
I think I might actually prefer ffprobe. ffmpeg is very useful to have on any system and is very easily installed on all (because it is found in most package managers). Installing it on Windows only requires the choco package manager and works like a charme. 
I haven't managed to install MediaInfo as a command line tool on windows that easily. Even with choco it installs a GUI Version which you'd then have to add to PATH etc....     
So if there is no other upside to MediaInfo I vote for ffprobe

**Comment by mdedwards** [comment]
I have no preference so just do whatever you want there. On 16. Mar 2024, at 20:08, Leon Focker ***@***.***> wrote:﻿
I think I might actually prefer ffprobe. ffmpeg is very useful to have on any system and is very easily installed on all (because it is found in most package managers). Installing it on Windows only requires the choco package manager and works like a charme.
I haven't managed to install MediaInfo as a command line tool on windows that easily. Even with choco it installs a GUI Version which you'd then have to add to PATH etc....
So if there is no other upside to MediaInfo I vote for ffprobe

**Comment by Leon-Focker** [comment]
Here is my suggestion for the regex part of it all:

```
(defun parse-ffprobe-data (string)
  (let* ((dur-scan (ppcre:create-scanner "Duration: \\d+:\\d+:\\d+.\\d+"
					 :single-line-mode t))
	 (audio-scan (ppcre:create-scanner "Audio.*?, \\d+ kb/s"
					   :single-line-mode t))
	 (chan-scan (ppcre:create-scanner ", \\d+ channels,"))
	 (srate-scan (ppcre:create-scanner ", \\d+ Hz,"))
	 (bit-scan (ppcre:create-scanner "\\d+ kb/s"))
	 (nr-scan (ppcre:create-scanner "\\d+\\.*(\\d+)*"))
	 (times '())
	 audio-stream
	 time
	 channels
	 srate
	 bitrate)
    ;; find times in hour, minute, seconds...
    (ppcre:do-matches-as-strings
	(match nr-scan (ppcre:scan-to-strings dur-scan string))
      (push (read-from-string match) times))
    (unless (= 3 (length times))
      (error "parse-ffprobe-data: duration malformed"))
    ;; find audio stream, then get channels, srate and bitrate from there,
    ;; then get only the numeric values
    (setf audio-stream (ppcre:scan-to-strings audio-scan string)
	  ;; convert duration to seconds
	  time (decimal-places
		(apply #'(lambda (hrs mins secs) (+ (* hrs 3600) (* mins 60) secs))
		       (reverse times))
		3))
    (unless audio-stream
      (error "parse-ffprobe-data: no Audio Stream found"))
    (setf channels (parse-integer
		    (ppcre:scan-to-strings
		     nr-scan
		     (ppcre:scan-to-strings chan-scan audio-stream)))
	  srate (parse-integer
		 (ppcre:scan-to-strings
		  nr-scan
		  (ppcre:scan-to-strings srate-scan audio-stream)))
	  bitrate (parse-integer
		   (ppcre:scan-to-strings
		    nr-scan
		    (ppcre:scan-to-strings bit-scan audio-stream))))
    (values time channels srate bitrate)))

(parse-ffprobe-data (shell-to-string "C:/ProgramData/chocolatey/bin/ffprobe.exe" "e:Los_4.wav"))

=> 464.58
=> 4 (3 bits, #x4, #o4, #b100)
=> 48000 (16 bits, #xBB80)
=> 6144 (13 bits, #x1800)
```

I tested this with .wav and .mp4

**Comment by rubenphilipp** [comment]
I agree with Leon, as I also find ffmpeg et al. extremely useful. 
The draft looks good to me at the first glance. Maybe we should also provide shortcut-functions to avoid multiple-value-binding?

**Comment by mdedwards** [comment]
Looking good but we don’t need bit rate at the moment rather but depth aka quantisation. 

we don’t need shortcut functions really as we’ll init sndfiles with all values plus separate functions would mean parsing four  times. Or am I misunderstand you?

**Comment by rubenphilipp** [comment]
> we don’t need shortcut functions really as we’ll init sndfiles with all values plus separate functions would mean parsing four times. Or am I misunderstand you?

For the internal use, that's true. But couldn't it be useful to add a function for quickly accessing the duration of an arbitrary soundfile (not sndfile) to the public interface?

**Comment by Leon-Focker** [comment]
I've got another Idea, which could easily satisfy both. Give me a minute!

**Comment by Leon-Focker** [comment]
```
(defun get-ffprobe-stream-info (argument &optional ffprobe)
  (lambda (filename)
    (nth-value 0
	       (read-from-string
		(shell-to-string (or ffprobe (get-sc-config 'ffprobe-command))
				 "-v" "error" "-select_streams" "a:0" "-show_entries"
				 argument
				 "-of" "default=noprint_wrappers=1:nokey=1"
				 filename)))))

(defun get-sound-srate (filename &optional ffprobe)
  (funcall (get-ffprobe-stream-info "stream=sample_rate" ffprobe)
	   filename))

(defun get-sound-bitdepth (filename &optional ffprobe)
  (funcall (get-ffprobe-stream-info "stream=bits_per_sample" ffprobe)
	   filename))

(defun get-sound-channels (filename &optional ffprobe)
  (funcall (get-ffprobe-stream-info "stream=channels" ffprobe)
	   filename))

(defun get-sound-duration (filename &optional ffprobe)
  (nth-value 0
	     (read-from-string
	      (shell-to-string (or ffprobe (get-sc-config 'ffprobe-command))
			       "-v" "error" "-show_entries"
			       "format=duration"
			       "-of" "default=noprint_wrappers=1:nokey=1"
			       filename))))

(defun get-sound-info (filename &optional ffprobe)
  (values (get-sound-duration filename ffprobe)
	  (get-sound-channels filename ffprobe)
	  (get-sound-srate filename ffprobe)
	  (get-sound-bitdepth filename ffprobe)))
```

This here is a totally regex-free version of the above. It is much cleaner and offers access to the individual information. Also, accessing the bit depth via regex is no fun, since its repesentation can change. However, talking to the shell takes time and here we need to do it 4 times instead of just one. So this does take about 4 times as long...

**Comment by Leon-Focker** [comment]
But, talking about speed seems a bit pointless when clm does it 100 times faster either way...

**Comment by rubenphilipp** [comment]
That's great! 

> But, talking about speed seems a bit pointless when clm does it 100 times faster either way

Partly, as our objective was to be able to be able to conditionally replace clm with a different procedure. I would definitelsy use clm's standard procedure, when the :clm feature is available and "fallback" to the ffbrobe solution if clm is not available. Could you implement something like this in your functions, @Leon-Focker ? 

In addition to this, we should definitely think about re-writing the (installation) documentation of sc. Is this worth a seperate issue? @mdedwards

**Comment by mdedwards** [comment]
Might I suggest a different approach? As we'll use this to init a sndfile object mostly, I would stick with the version that returns four values. That way we only have the shell overhead once.

For the single-value functions, you simply call the main function and nth-value as you do above.


By the way, are you putting this code into the repo? And taking care of the #-clm stuff to use CLM when it's there, otherwise your code?

BTW2: did you check this with videos yet? Should be a no-brainer, right? That's going to be a game-changer: reaper-play algorithmically placing videos!  (For now though, unless you object, we'll treat a video as a sndfile, as we're not interested it its video data. Or we could be a little more clever and create a video class which is a subclass of sndfile. Might be cleaner.)

**Comment by mdedwards** [comment]
Or cleaner again, a media file class of which sndfile and video are subclasses. That would need some thought and reprogramming of sndfile-palette

**Comment by mdedwards** [comment]
of course Leon if you want to avoid the regexp version then go with your four functions which call the shell one time each. I don’t think it’s going to be such a big deal in terms of speed. In that case though we don’t need the four values version as that would just be a little more effort with multiple value bind to be honest. We can just stick with the four functions. However, I would use the hash plus and minus syntax to use CLM if it’s available, otherwise ffprobe, and of course to issue an error if neither are available. That might need an auxiliary function to make things easier.

**Comment by Leon-Focker** [comment]
I've been testing everything with .wav and .mp4 files so far. I will add the optional CLM now and add all of this into the repo. Any suggestions as to where?

**Comment by mdedwards** [comment]
Nice. Whack it all in sndfile.lsp

**Comment by Leon-Focker** [comment]
Turns out there was a beautiful solution afterall: [b89c800](https://github.com/mdedwards/slippery-chicken/commit/b89c8004ac559f52290c64cd153bb21f94550057)

The only weird thing is clm's sound-bits-per-sample, as it seems to get the bitdepth wrong a lot of times... Not sure if there is an alternative (except ffprobe et al.)?

**Comment by mdedwards** [comment]
Nice! Thanks.  Well here's the thing: CLM also won't get sound file data for video files either (if I remember correctly, it doesn't throw an error). So we'll need to use more logic than #+clm can offer us. We might need a class-based solution. Do you need some help with that?

**Comment by Leon-Focker** [comment]
Ah. So that the user would manually discern between video and soundfile or should we try and detect it by file type? 

As long as a new mediafile class would never handle media without an audio stream, we could just rename the current sndfile class to mediafile and then make a sndfile its subclass. So far so easy. The complicated part (deciding on how sndfile-palettes and everything else interacts with mediafiles) probably needs a lot of discussion. 

Also I don't think I'll get to doing any of that this week, as I'll be trying to take some vacation days ;)

**Comment by mdedwards** [comment]
> Ah. So that the user would manually discern between video and soundfile or should we try and detect it by file type?

They could of course, but as these are mainly used in sndfile-palettes we'd detect and init accordingly.

Does ffprobe have a way of distinguishing between sound files and videos? E.g. via mime-type, as with web pages?

If not then we can just go via extension (.wav .mov etc.) but that's not as robust of course.

> As long as a new mediafile class would never handle media without an audio stream,

well theoretically it could of course but maybe we'll just start with adding videos

> we could just rename the current sndfile class to mediafile and then make a sndfile its subclass. 

Actually I'd leave sniffle as it is, as many of its properties wouldn't be applicable to a generic media file

> So far so easy. The complicated part (deciding on how sndfile-palettes and everything else interacts with mediafiles) probably needs a lot of discussion.

Not so much. This is how I'd start:

- make a vidfile class that is a subclass of sndfile-ext
- maybe add some useful slots like bitrate, encoding type, picture dimensions etc. but leave all the associated functionality open for now
- if we can't auto-detect via ffprobe/mime-type, in the sndfile-palette add video-file extensions like .mov so that we can distinguish between them
- in sndfile-palette's verify-and-store replace the make-sndfile-ext calls with a more generic function that decides whether to make a sndfile-ext or vidfile 
- from then on we can use vidfiles just like sndfiles when it comes to reaper at least, but of course not in CLM
 - maybe when making vidfiles we issue a warning that a video was detected and that it can't be used in clm-play (elsewhere??)

> Also I don't think I'll get to doing any of that this week, as I'll be trying to take some vacation days ;)

Good plan. Have fun.

All the best, Michael

**Comment by Leon-Focker** [comment]
Getting information about the mediafile is very easy with ffprobe. See for example:
```
(shell-to-string (get-sc-config 'ffprobe-command) "-loglevel" "error" "-show_entries" "stream=codec_type" "-of" "default=nw=1" "E:/SWELST/video/C0002.MP4")
=> "codec_type=video
codec_type=audio
codec_type=data
codec_type=data
"

(shell-to-string (get-sc-config 'ffprobe-command) "-loglevel" "error" "-show_entries" "stream=codec_type" "-of" "default=nw=1" "e:/Los_5.wav")
=> "codec_type=audio
"
```
However, calling the shell really takes a long time (relatively). I would rather have an option to check with ffprobe to be certain, but use file extensions as a default. Else, loading 100s of soundfiles with a .wav type would be considerably slower with no gain...

**Comment by mdedwards** [comment]
OK so we'd just need to scan the returned string for 'video' or 'audio'. An option for ffprobe vs extension would be easy to implement.

**Comment by Leon-Focker** [comment]
One more thing about get-sound-info:
I just noticed, that the update method for sndfile-ext has to be rewritten as well. And in there we currently call 
`(* 8 (clm::sound-datum-size)) (clm::sound-framples) (clm::sound-length)`
for which I have no counterpart in (get-sound-info).

Should I try and update (get-sound-info) to include these or should we just ignore all the slots that the sndfile-ext update method sets (because then we are calling (get-sound-info) a second time, which is even more slow...)?

**Comment by Leon-Focker** [comment]
I agree, changing the slot name might help.

We actually are back to a single shell call -- without regex -- because now get-sound-info only collects the relevant information in one ffprobe call. But there is a sndfile/update method and a sndfile-ext/update method. When calling make-sndfile-ext, both are called and thus we call get-sound-info twice and thus spawn a shell environment twice... But that won't kill nobody.

**Comment by mdedwards** [comment]
gotcha. all good in the 'hood then no? you want to take charge of this stuff? Of course once you're there I can handle the new class and the video recognition stuff if you're not happy to take that on

**Comment by Leon-Focker** [comment]
I updated the get-sound-info function to include size and frample-count. I also updated the sndfile-ext/update method. I didn't yet rename the bitrate slot. If you want to handle the new classes etc. that would be great. If there is more to do next week I'll get on board again ;)

**Comment by mdedwards** [comment]
I assume you ran the tests too but sadly this one now fails:

test-sndfile-get-sound-info

with this backtrace:


illegal terminating character after a colon: #\

  Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "dyld[523...">
   [Condition of type SB-INT:SIMPLE-READER-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {7001F100A3}>)

Backtrace:
  0: (SB-IMPL::READ-TOKEN #<SB-IMPL::STRING-INPUT-STREAM {4756E23}> #\d)
  1: (SB-IMPL::READ-MAYBE-NOTHING #<SB-IMPL::STRING-INPUT-STREAM {4756E23}> #\d)
  2: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SB-IMPL::STRING-INPUT-STREAM {4756E23}> NIL (NIL) T)
  3: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SB-IMPL::STRING-INPUT-STREAM {4756E23}> NIL (NIL) NIL)
  4: (READ #<SB-IMPL::STRING-INPUT-STREAM {4756E23}> NIL #:EOF NIL)
  5: (STRING-TO-LIST "dyld[52395]: Library not loaded: /usr/local/opt/libvmaf/lib/libvmaf.1.dylib ..)
  6: (GET-SOUND-INFO "/Users/michael/Library/Mobile Documents/com~apple~CloudDocs/sc/tests/pink5s.wav" T)
  7: (TEST-SNDFILE-GET-SOUND-INFO)

**Comment by Leon-Focker** [comment]
Oh, interesting... What do you get when calling this:
`(shell-to-string (get-sc-config 'ffprobe-command) (get-test-sf-path "tests/pink5s.wav"))`
The backtrace suggests the problem lies within string-to-list...

**Comment by mdedwards** [comment]
List-to-string was from Dan. Do we want to hassle him about this?

I get the following:

(shell-to-string (get-sc-config 'ffprobe-command) (get-test-sf-path "tests/pink5s.wav"))
"ffprobe version N-110020-g0d35634eaa Copyright (c) 2007-2023 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.102)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/HEAD-0d35634 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --enable-opencl --enable-audiotoolbox --enable-videotoolbox --disable-htmlpages --enable-libfdk-aac --enable-nonfree
  libavutil      58.  3.100 / 58.  3.100
  libavcodec     60.  6.101 / 60.  6.101
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  4.100 /  9.  4.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, wav, from '/Users/michael/Library/Mobile Documents/com~apple~CloudDocs/sc/tests/pink5s.wav':
  Duration: 00:00:05.00, bitrate: 774 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 1 channels, s16, 768 kb/s
"

**Comment by Leon-Focker** [comment]
Okay so the ffprobe seems to do what it should...
I guess there is a weird character somewhere -- and only in your version of this call -- that string-to-list can't handle. Fixinng this might be as easy as adding a character encoding somewhere... Dunno :d 

Do you want to investigate that? Because I have never had this error (on 3 different systems). Else I will look into it next week...

**Comment by mdedwards** [comment]
Oh here's a weird one: after saving on my machine and rerunning it passes! I think that is a weird character, probably related to the \n\r stuff we were facing recently. Could it be that you last saved sc-test-suite.lsp on windows before checking in? If so, then probably we should only save and check in from a unix machine as going that way seems not cause problems (right?)

**Comment by Leon-Focker** [comment]
I thought about that, too, but I was checking in on my unix.... Now that I think about it though, maybe i copied some line from windows -- to then commit on unix.... Gosh that OS will be the end of me!

**Comment by Leon-Focker** [comment]
But for Ruben and me the tests were passing anyways, which would be weird in that case..... IDK!

**Comment by mdedwards** [comment]
Maybe UBUNTU handles newlines in a more catholic fashion. I don't think any of use are sure why it happened for me on MacOS but I ran it several times after restarting lisp. It only went away once I'd saved files on my Mac.

**Comment by Leon-Focker** [comment]
Just to be sure tho: Currently the test is commented out in the repo. When you say you saved your file, does that include the test without #| |#?

**Comment by mdedwards** [comment]
Pretty sure I uncommented that this morning. Just forced another push and it’s there.

**Comment by Leon-Focker** [comment]
Hm, I have no explanation then. Lets keep an eye on it I guess...

**Comment by mdedwards** [comment]
>Should I try and update (get-sound-info) to include these or should we just ignore all the slots that the sndfile-ext update method sets (because then we are calling (get-sound-info) a second time, which is even more slow...)?

Good eyes and good question. I've just updated the sndfile-ext class update method to call `get-sound-info` and pass that list to the parent class's method so it's only called once. It's a nice example of an :around method if you're not already familiar with that.

**Comment by mdedwards** [comment]
I reckon we can close this now, no?
