### ISSUE TITLE
removing ppcre workaround on quicklisp branch

### ISSUE THREAD

**Issue by Leon-Focker** [mdedwards/slippery-chicken#83]
When using asdf to manage the slippery-chicken system, the workaround for automatically cloning ppcre (see [41906ba](https://github.com/mdedwards/slippery-chicken/pull/66/commits/41906ba01d89af96cdf32d2afde363f6af7b4efc)) could be reverted to using asdf.

**Comment by rubenphilipp** [comment]
As the .asd now depends on `cl-ppcre`, try to remove (uncomment) `(sc::import-ppcre)` wherever it is defined (didn't check).

**Comment by Leon-Focker** [comment]
Currently import-ppcre is defined in utilities and called in all.lsp
Since all.lsp is ignored when using the .asd, we might leave everything as is for now?

**Comment by rubenphilipp** [comment]
This sounds sane. I'd suggest adding a note in the header comment mentioning that this file is not relevant when using asdf.

**Comment by mdedwards** [comment]
As import-ppcre is only used in all.lsp I've taken it out of utilities.lsp and put it in all.lsp instead. 

Hell, I've also removed the cm-2.6.0 folder.

All tests passing. Closing.
