### ISSUE TITLE
control-wave.lsp fails to build

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#85]
Curiously I am getting an error with control-wave.lsp in my new .asd (cf. #81) that never occurred when when loading sc the "old way". It appears that sbcl is not happy with the type declaration (integer) and the initform (nil) of `period`. I have fixed this on a commit on the *quicklisp* branch (cf. https://github.com/mdedwards/slippery-chicken/commit/cd228891ce85b24e7bc20c3cbf6c4732c104a724) by removing the type definition from the period slot and adding an additional sanity check. 
Tests are running, though I'd appreciate further review…

```
control-wave.lsp:66:4:
  warning: 
    Constant NIL conflicts with its asserted type INTEGER.
    See also:
      SBCL Manual, Handling of Types [:node]

control-wave.lsp:177:1:
  style-warning: 
    IGNORE declaration for an unknown variable: IGNORE
    --> EVAL-WHEN SB-PCL::%DEFMETHOD-EXPANDER SB-PCL::LOAD-DEFMETHOD 
    --> SB-PCL::LOAD-DEFMETHOD LIST* LET* SB-INT:NAMED-LAMBDA FUNCTION 
    --> SYMBOL-MACROLET SB-PCL::FAST-LEXICAL-METHOD-FUNCTIONS 
    --> SB-PCL::BIND-FAST-LEXICAL-METHOD-FUNCTIONS FLET LET 
    --> SB-PCL::BIND-ARGS 
    ==>
      (LET* ((SB-PCL::.ARGS-TAIL. NIL) (SB-PCL::.DUMMY0.))
        (DECLARE (IGNORABLE SB-PCL::.ARGS-TAIL. SB-PCL::.DUMMY0.))
        (DECLARE (IGNORE IGNORE))
        (DECLARE
         (SB-PCL::%CLASS SLIPPERY-CHICKEN::CW SLIPPERY-CHICKEN::CONTROL-WAVE))
        (LOCALLY
         (DECLARE (DISABLE-PACKAGE-LOCKS SB-PCL::%PARAMETER-BINDING-MODIFIED))
         (SYMBOL-MACROLET ((SB-PCL::%PARAMETER-BINDING-MODIFIED #))
           (DECLARE (ENABLE-PACKAGE-LOCKS SB-PCL::%PARAMETER-BINDING-MODIFIED))
           (BLOCK SLIPPERY-CHICKEN::GET-DATA
             (LET #
               #)))))
```

**Comment by mdedwards** [comment]
Yeah, well, that's weird that the error wasn't picked up before but it's good that it's gone now. Fine with me. Closing (hope that's OK).

**Comment by rubenphilipp** [comment]
👍Am 16.03.2024 um 11:11 schrieb Michael Edwards ***@***.***>:﻿
Yeah, well, that's weird that the error wasn't picked up before but it's good that it's gone now. Fine with me. Closing (hope that's OK).
