### ISSUE TITLE
salzedo warnings

### ISSUE THREAD

**Issue by mdedwards** [mdedwards/slippery-chicken#86]
Hi Ruben, the asdf compile procedure is revealing lots of interesting warnings. One advantage of asdf at least ;-) 

I'm fixing loads right now but thought you might want to look at this one below.

best, Michael

; in: DEFMETHOD SUBSET-FROM-HARP-SALZEDO (SC-SET T)
;     (DEFMETHOD SLIPPERY-CHICKEN::SUBSET-FROM-HARP-SALZEDO
;                ((SLIPPERY-CHICKEN::S SLIPPERY-CHICKEN::SC-SET)
;                 SLIPPERY-CHICKEN::SALZEDO
;                 &KEY SLIPPERY-CHICKEN::ID
;                 (SLIPPERY-CHICKEN::LOWEST 'SLIPPERY-CHICKEN::B0)
;                 (SLIPPERY-CHICKEN::HIGHEST 'SLIPPERY-CHICKEN::GS7)
;                 SLIPPERY-CHICKEN::AS-SYMBOLS SLIPPERY-CHICKEN::SUBSETS
;                 SLIPPERY-CHICKEN::RELATED-SETS (SLIPPERY-CHICKEN::AUTO-SORT T))
;       (LET* ((SLIPPERY-CHICKEN::SALZEDO-SET
;               (SLIPPERY-CHICKEN::HARP-SALZEDO-TO-TL-SET SLIPPERY-CHICKEN::SALZEDO
;                :HIGHEST SLIPPERY-CHICKEN::HIGHEST :LOWEST
;                SLIPPERY-CHICKEN::LOWEST))
;              (SLIPPERY-CHICKEN::SALZEDO-SET-PITCHES
;               (SLIPPERY-CHICKEN::DATA SLIPPERY-CHICKEN::SALZEDO-SET))
;              (SLIPPERY-CHICKEN::SET-PITCHES
;               (SLIPPERY-CHICKEN::DATA SLIPPERY-CHICKEN::S))
;              (SLIPPERY-CHICKEN::SUBSET
;               (SLIPPERY-CHICKEN::PITCH-INTERSECTION SLIPPERY-CHICKEN::SET-PITCHES
;                                                     SLIPPERY-CHICKEN::SALZEDO-SET-PITCHES)))
;         (IF SLIPPERY-CHICKEN::AS-SYMBOLS
;             (MAPCAR #'SLIPPERY-CHICKEN::DATA SLIPPERY-CHICKEN::SUBSET)
;             (SLIPPERY-CHICKEN::MAKE-SC-SET SLIPPERY-CHICKEN::SUBSET :ID
;              SLIPPERY-CHICKEN::ID))))
; --> EVAL-WHEN SB-PCL::%DEFMETHOD-EXPANDER SB-PCL::LOAD-DEFMETHOD 
; --> SB-PCL::LOAD-DEFMETHOD LIST* LET* SB-INT:NAMED-LAMBDA 
; ==>
;   #'(SB-INT:NAMED-LAMBDA (SB-PCL::FAST-METHOD
;                           SLIPPERY-CHICKEN::SUBSET-FROM-HARP-SALZEDO
;                           (SLIPPERY-CHICKEN::SC-SET T))
;         (SB-PCL::.PV. SB-PCL::.NEXT-METHOD-CALL. SLIPPERY-CHICKEN::S
;          SLIPPERY-CHICKEN::SALZEDO &KEY SLIPPERY-CHICKEN::ID
;          (SLIPPERY-CHICKEN::LOWEST 'SLIPPERY-CHICKEN::B0)
;          (SLIPPERY-CHICKEN::HIGHEST 'SLIPPERY-CHICKEN::GS7)
;          SLIPPERY-CHICKEN::AS-SYMBOLS SLIPPERY-CHICKEN::SUBSETS
;          SLIPPERY-CHICKEN::RELATED-SETS (SLIPPERY-CHICKEN::AUTO-SORT T) ...)
;       (DECLARE (IGNORABLE SB-PCL::.PV. SB-PCL::.NEXT-METHOD-CALL.)
;                (DISABLE-PACKAGE-LOCKS SB-PCL::PV-ENV-ENVIRONMENT))
;       (DECLARE
;        (SB-C::CURRENT-DEFMETHOD SLIPPERY-CHICKEN::SUBSET-FROM-HARP-SALZEDO NIL
;         (SLIPPERY-CHICKEN::SC-SET T)
;         (SLIPPERY-CHICKEN::S SLIPPERY-CHICKEN::SALZEDO &KEY
;          SLIPPERY-CHICKEN::ID (SLIPPERY-CHICKEN::LOWEST #)
;          (SLIPPERY-CHICKEN::HIGHEST #) SLIPPERY-CHICKEN::AS-SYMBOLS
;          SLIPPERY-CHICKEN::SUBSETS SLIPPERY-CHICKEN::RELATED-SETS
;          (SLIPPERY-CHICKEN::AUTO-SORT T))))
;       (DECLARE
;        (SB-C::SOURCE-FORM
;         (LAMBDA
;             (SLIPPERY-CHICKEN::S SLIPPERY-CHICKEN::SALZEDO
;              &KEY SLIPPERY-CHICKEN::ID # # SLIPPERY-CHICKEN::AS-SYMBOLS
;              SLIPPERY-CHICKEN::SUBSETS SLIPPERY-CHICKEN::RELATED-SETS #)
;           (LET* #
;             #))))
;       (DECLARE (SB-PCL::%PARAMETER SLIPPERY-CHICKEN::SALZEDO))
;       (DECLARE (SB-PCL::%PARAMETER SLIPPERY-CHICKEN::S))
;       (DECLARE (TYPE T SLIPPERY-CHICKEN::SALZEDO))
;       (DECLARE (IGNORABLE SLIPPERY-CHICKEN::SALZEDO SLIPPERY-CHICKEN::S))
;       (SYMBOL-MACROLET ((SB-PCL::PV-ENV-ENVIRONMENT SB-PCL::DEFAULT))
;         (SB-PCL::FAST-LEXICAL-METHOD-FUNCTIONS ((SLIPPERY-CHICKEN::S
;                                                  SLIPPERY-CHICKEN::SALZEDO)
;                                                 SB-PCL::.NEXT-METHOD-CALL.
;                                                 (SLIPPERY-CHICKEN::S
;                                                  SLIPPERY-CHICKEN::SALZEDO)
;                                                 NIL :CALL-NEXT-METHOD-P NIL
;                                                 :SETQ-P NIL :PARAMETERS-SETQD
;                                                 NIL :METHOD-CELL
;                                                 (#:METHOD-CELL) ...)
;           (DECLARE
;            (SB-PCL::%CLASS SLIPPERY-CHICKEN::S SLIPPERY-CHICKEN::SC-SET))
;           (LOCALLY
;            (DECLARE #)
;            (SYMBOL-MACROLET #
;              #
;              #)))))
; 
; caught STYLE-WARNING:
;   The variable SUBSETS is defined but never used.
; 
; caught STYLE-WARNING:
;   The variable RELATED-SETS is defined but never used.

;     (SLIPPERY-CHICKEN::AUTO-SORT T)
; 
; caught STYLE-WARNING:
;   The variable AUTO-SORT is defined but never used.
WARNING:
   Lisp compilation had style-warnings while
   compiling #<CL-SOURCE-FILE.LSP "slippery-chicken" "sc-set">

**Comment by rubenphilipp** [comment]
Sure, I will have a look at it and to the necessary changes. Please let me know, if you find other issues with code of mine while reading our new best selling novel… ;)
