### ISSUE TITLE
Implement asdf:test-system

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#88]
Currently, the RT-mechanism for sc still works as usual by evaluation e.g. `(run-tests)`. As ASDF has got its own convention (`(asdf:test-system)`), it might be useful to also be able to run the tests via ASDF's own command.

**Comment by mdedwards** [comment]
Can't test-system just call run-tests? Go ahead and add/do that if you like.

**Comment by rubenphilipp** [comment]
I already tried this, when I wrote the .asd. But maybe I did some stupid mistake. I'll try this again now…

**Comment by rubenphilipp** [comment]
Okay, I needed to define a second system ("slippery-chicken/tests"), which does not contain (as of now) any components itself but just provides a `test-op` which calls `run-tests` from the main system (cf. a3d9ed7). It works on my machine, though I'd appreciate you to try `(asdf:test-system :slippery-chicken)`.

**Comment by mdedwards** [comment]
Perfect! Thanks. run-tests is being called and passes.

**Comment by rubenphilipp** [comment]
Fine. So I'll close this issue.
