### ISSUE TITLE
pause-last doc

### ISSUE THREAD

**Issue by mdedwards** [mdedwards/slippery-chicken#9]
Hey Dan, could you add robdoc to your new method? thanks, Michael

**Comment by mdedwards** [comment]
Thanks for the doc Dan. Pull the latest source and check my changes to your method and your documentation. I've used you full name under AUTHOR (but note that robodoc doesn't (yet) pull that tag out of the source code). I've also added a new keyword arg. Note the way I document those.

(This is also in the test suite so nothing to do there.)

**Comment by danieljamesross** [comment]
Oh yes, good extra arg. Also, doc methodology noted!

**Comment by mdedwards** [comment]
Thanks Dan.
