### ISSUE TITLE
run-tests

### ISSUE THREAD

**Issue by mdedwards** [mdedwards/slippery-chicken#91]
We need to call run-tests on Mac, Linux, and Windows, with just the barebones system (i.e. no CMN or CLM), then with just CMN, then just CLM. In particular the reaper-play tests need to pass eventually without CLM. On all systems.

**Comment by Leon-Focker** [comment]
This seems like a good place to dump all my Windows testing troubles then! The next hurdle is lilypond - I think there is no easy way to use it on Windows as you would on Mac, right? And because of that, tests calling lp-display currently fail on my Windows.

**Comment by mdedwards** [comment]
As you know, lp-display is merely a convenience function for those systems on which we can call system-open-file. If you can get the latter working on windows then I see  no reason why lp-display and all other methods like midi-play can't open their files after generating them. However lp-display should not be called in the tests if they are to run on windows. Ruben and I were guilty however :/ So I've just changed those to look something like this:

```#+sc-auto-open (lp-display sc :base-path "/tmp/"))
#-sc-auto-open (write-lp-data-for-all sc :base-path "/tmp/")```

**Comment by Leon-Focker** [comment]
Soooooo good news!
Windows is almost happy when testing, but! I have found a new fun feature:
```
(floor -.31 .01)
=> -32
=> 0.00999999
```
And that is precisely why (test-utilities-get-harmonics) fails on windows because:
```
(get-harmonics (note-to-freq 'c3) :notes t
                           :max-freq (note-to-freq 'f6))

=>` ((C3 0) (C4 0) (G4 2) (C5 0) (E5 -14) (G5 2) (BF5 -32) (C6 0) (D6 4) (E6 -14))

(equalp (get-harmonics (note-to-freq 'c3) :notes t
                           :max-freq (note-to-freq 'f6))
            '((C3 0) (C4 0) (G4 2) (C5 0) (E5 -14) (G5 2) (BF5 -31) (C6 0)
              (D6 4) (E6 -14)))
```
What should we do about that? :)

**Comment by mdedwards** [comment]
Ooh bizarre! Windoze is in the wrong there, no? This is MacOS SBCL:

```(floor -.31 .01)
-31
0.0
SC> (/ -.31 .01)
-31.0```

That should be the same result with ANSI Lisp on any OS. Have you scoured the net for suggestions around this? Worth posting to the SBCL team?

Until they are consistent I would suggest using some #+windows wizardry to represent the difference. As it's only 1 cent difference it's below the Just Noticeable Difference of c. 2 cents if I remember correctly.

**Comment by Leon-Focker** [comment]
Turns out I had an old version of sbcl running on my laptop (which I was doing this on). Updating SBCL fixed this and now I can happily report that (run-tests) goes smoothly on Windows! 
![yay](https://github.com/mdedwards/slippery-chicken/assets/83008122/15a2f7a4-ee98-4f9c-8788-e4ac245a2906)
