### ISSUE TITLE
sc Compile and load

### ISSUE THREAD

**Issue by mdedwards** [mdedwards/slippery-chicken#92]
Do we still need that old fun in the asd file?

**Comment by rubenphilipp** [comment]
As of now, yes. I've pointed the reason out in the .asd discussion (https://github.com/mdedwards/slippery-chicken/issues/81#issuecomment-2000599041):
> The function cl-user::sc-compile-and-load is in essence not required as ASDF does this job for us now (at least I thought so for one hour). But as cm.lsp (re-)uses this function in order to refresh the diapason, I (re-)implemented it in our .asd file with some major modifications[2](https://github.com/mdedwards/slippery-chicken/issues/92#user-content-fn-2-31a992dd676c716a630d7978e250b135). Different from the previous version, cl-user::sc-compile-and-load now uses ASDF's function to determine the output location and extension of the binaries.

We could, of cause, easily change the behavior of `cm.lsp` if desired to use ASDF-paths for re-compilation.

**Comment by mdedwards** [comment]
I understand but isn't that 'auf Spazen mit Kanonen zu schiessen'? I think `set-diapason` is the only function that now uses sc-compile-and-load so we really don't need that extended functionality now.  I've changed that function to use `(load (file-from-sc-dir "src/cm-load.lsp"))` instead so if you're happy, then you can take that ugly function out of your beautiful .asd file ;-)

**Comment by mdedwards** [comment]
by the way, as you know I finally have embraced ASD but I don’t think we should scatter calls to ASD code throughout the slippery-chicken source code, in order to for example load files et cetera. It could easily be that ASD dies at some point or we find a better solution and I don’t want to have to get rid of the pollution in my  otherwise fairly ANSI standard lisp code

**Comment by rubenphilipp** [comment]
Thanks, Michael! 
I also agree with you concerning to rather strictly separate ASDF-code from ANSI common lisp code. Shall I try to find a solution for the ASDF-related variable declarations in globals.lsp?

**Comment by mdedwards** [comment]
Ach thanks but I only see cl-user::+slippery-chicken-src-path+ there and we have more important fish to fry for now so let's face that problem if we ever say farewell to asdf---which is unlikely, probably...

**Comment by rubenphilipp** [comment]
Done.
