### ISSUE TITLE
RTs for reaper-play are missing

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#95]
Hello Michael,

while testing our system without clm being present to the `*features*` I have noticed that there are no prober tests for `reaper-play` in the test-suite. As of now, this method is just tested implicitly in `test-player-ambitus` and `test-clm-play-with-subsections` – the latter being ignored via the feature tag. Should we add some tests for `reaper-play`?

Best
Ruben

**Comment by mdedwards** [comment]
Yes for sure! Actually if I'm not mistaken, until Leon's ffprobe functionality is complete all tests of reaper-play should be within a #+clm as the sndfile-palette needs clm to get durations. Or maybe it will work already?

In any case we should definitely add some more reaper-play tests for when clm is not present once we're at that point.

**Comment by rubenphilipp** [comment]
Okay. That sounds reasonable. So then let's probably wait with the reaper-play tests until we've finished the work on sndfile/mediafile.
Testing `reaper-play` implicitly, as described above, works with and without clm.

**Comment by rubenphilipp** [comment]
Nice. The tests run smoothly on my machine.
By the way: Very tastefully curated test videos… ;)

**Comment by mdedwards** [comment]
Am closing now but if you have any (more tasteful) videos to add to the tests I'd be grateful for the input (and the regression tests).
