### ISSUE TITLE
Please test: spec-an and ctlwav now loaded via get-clm-ins

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#98]
As I have got problems with control-wav-ins.lsp and get-spectrum.lsp being loaded via the .asd-file (the same with system restart as with samp5 and sine), I also used the new function `get-clm-ins` in all files which use the respective instrument.
Tests run on my system. If the same applies to yours, feel free to close this issue.

**Comment by rubenphilipp** [comment]
> I guess that needs to be tested on a 'virgin' system

Definitely. I try to rather frequently delete the cached files and restart my system in order to more or less emulate a "fresh" system. But we should definitely do some more proper testing with fresh installs on different OSs. 

> I think I added all necessary get-clm-ins calls

Okay, that's interesting as I did not find them in my repo. To quickly summarize my issues: control-wav-ins.lsp and get-spectrum.lsp were – prior to this commit – still loaded via the .asd file. This lead to the problem we had before (see our discussion in the defscins issue) that the respective .so files get lost after a system restart but not recreated when `(asdf:load-system` as asdf assumes nothing is to be compiled as the fasls in the cache are still valid. This is proper behaviour as asdf is not expected to be aware of the fact that we also compile things to the `*clm-c-direcory*`. But when trying to call e.g. `get-spectrum`, SBCL complains about a missing .so file. This is solved now (as with samp5 and sine) by using your new function to compile and load clm instruments instead of the asdf routine. To do so, I needed (cf. commit) to add the function call to a number of files which use the instrument. These were not present at the time I was working on this issue.

**Comment by mdedwards** [comment]
OK I believe you Ruben! I'm no longer sure who added what when as I've been doing a thousand complex things to get video files incorporated and speed up reaper-play (did you see that speed increase yet?). But whoever did it, the right things are being loaded by asdf and `get-clm-ins` now, right? So we're all happy?

**Comment by rubenphilipp** [comment]
Sure. I just wanted to make sure that I did not make any mistake. But everything works fine on my side, too. And yes, I did notice major performance improvements. Well done!

**Comment by rubenphilipp** [comment]
Ah, now I made a mistake and reopened the already closed issue… Will revert this now.
