### ISSUE TITLE
Using slippery chicken the old way

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#99]
Hello,

one more issue related to our new quicklisp-version. 
Did anybody test whether the new main branch can be loaded the old way (via all.lsp)? I was just wondering because we also made a few changes in the sc source and I used ASDF most of the time. 
I also think it might be a good idea to issue a warning when loading all.lsp that this method is deprecated now. This would then also inform all sc-users who just get their updates by pulling and thus don't notice "naturally" that there have been some structural changes to the software. 

Best
Ruben

**Comment by mdedwards** [comment]
I just tried it now and it fails with:

The function SLIPPERY-CHICKEN::IMPORT-PPCRE is undefined.

@Leon-Focker ?

**Comment by rubenphilipp** [comment]
Could it be that moving the function definition to all.lsp caused the problem? As far as I see it, `import-ppcre` is defined in the cl-user namespace, not sc. 

https://github.com/mdedwards/slippery-chicken/issues/83#issuecomment-2002342459

**Comment by mdedwards** [comment]
Well, you have to suck it and see, sometimes. We didn't know back then just how much had to change. I really don't think we even need a warning/error even but have no problem if you want to add that. Users of the old system / way of starting sc will simply have to switch to asdf or use the old (tagged) version.

**Comment by rubenphilipp** [comment]
That's true. I am glad that we noticed this. 
Will you remove the file and the references to the old method? We also need to add a note to the wiki-entry that it is deprecated as of version 1.1.0. 
I understand that you deem an error to be unnecessary. Though, I am afraid that some users would be rather irritated when being confronted with an error indicating a missing file and probably seeking the error on their side. If it is okay for you, I will created such a "fake" all.lsp after we removed the old one.

**Comment by Leon-Focker** [comment]
Heyo. Removing the current all.lsp seems like the right decision. With the new install script, nobody should habe troubles. I like @rubenphilipp s idea. Just point to the slippery-chicken.asd and the install.md ...

Else, just pulling unknowingly without looking on github might cause frustration.

**Comment by rubenphilipp** [comment]
I've already edited the wiki entry: 
https://github.com/mdedwards/slippery-chicken/wiki/how-to-install-slippery-chicken-'by-hand'

**Comment by mdedwards** [comment]
> Will you remove the file and the references to the old method? 

Where else besides that wiki entry is it mentioned? I can't think of any place.

>  If it is okay for you, I will created such a "fake" all.lsp after we removed the old one.

No need to remove the old then create a new one with the same name. I've just deleted the contents of all.lsp and added an error message. That should suffice.

**Comment by rubenphilipp** [comment]
> Where else besides that wiki entry is it mentioned? I can't think of any place.

It's mentioned in the readme and install.md. 

> No need to remove the old then create a new one with the same name. I've just deleted the contents of all.lsp and added an error message. That should suffice.

Alright. I will write the error message then.

**Comment by mdedwards** [comment]
Huh? As I wrote: I've just deleted the contents of all.lsp and added an error message.

**Comment by rubenphilipp** [comment]
Ups. Missed that. Pardon!

**Comment by mdedwards** [comment]
> It's mentioned in the readme and install.md.

Ah OK, I thought you meant all.lsp but you probably mean installation 'by hand'.  I've deleted references to that in the .md files

**Comment by JRSV** [comment]
Hello Michael,

I just bumped into this update, and to tell you the truth its a bit difficult to install for me, I think there are a couple of basic steps missing for someone a bit lost like me. ASDF is installed and executed in emacs? this is after having SBCL and SLIME? sorry, I know this is a bit basic, but I do not know where to begin. Can there be a set of instructions that refer to installing everything from emacs... the very beginning? I installed SBCL and ran (find :asdf *features*) and got:

`debugger invoked on a UNBOUND-VARIABLE @B80066F924 in thread
#<THREAD tid=36785 "main thread" RUNNING {1000B98003}>:
  The variable *FEATURES is unbound.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE   ] Retry using *FEATURES.
  1: [USE-VALUE  ] Use specified value.
  2: [STORE-VALUE] Set specified value and use it.
  3: [ABORT      ] Exit debugger, returning to top level.
`

again, sorry for this, I was excited to upgrade SC and failed immediately.

any hep would be appreciated

**Comment by mdedwards** [comment]
Hello Rafael, I think you just made a typo. What you wanted was  (find :asdf *features*)  The asterisks are essential.

Honestly I think Ruben wrote a great installation page. The long version is already very detailed. I believe the philosophy is to avoid assuming the user uses Emacs with slime/sly — although almost all of us do — you make the choice there. How to install those things belong on their respective pages. From that point I would (now) look at quicklisp’s instruction page on how to get that working, then take sc installation from there—it should then be pretty easy.

Best, Michael

**Comment by JRSV** [comment]
Hello Michael,

yes, it was a typo. either way, now that command says NIL, so of to downloading and installing asdf.
I DO understand what you mean about emacs or other IDE, the idea of showing all steps including the IDE is to understand what you need first. I feel that the other method was friendlier with newbies. I will give it another go... I am still a bit confused. If I am successful I can maybe do a video for you to upload to youtube sc channel as a basic help? if interested of course. If I continue to fail, I will open a new thread to ask for more help. 

cheers

**Comment by JRSV** [comment]
hello @rubenphilipp 

yes, I tried to install it following those instructions, I ended up in this thread after failing. The instructions confidently say ASDF is probably there, but to my surprise, its not (I am on a linux machine debian 12 based) The problem starts at the very beginning, my first yellow light came here:

 "this document assumes that you have a working Common Lisp implementation running on your system as well as that you have a basic understanding of the Common Lisp language"

so I assumed I had to go ahead and install SBCL myself, and SLIME if I was going to evaluate thing in emacs. So I begun with SBCL and decided to check ASDF and no luck. There is where I stopped as my day was done by then. Now I will resume trying this. I just started downloading ASDF binary package and will try again soon. Although the directories mentioned are not really there, I have no (~/common-lisp/ or ~/.local/share/common-lisp/source/) directories, I will see if by just adding them is fine or if I need SBCL and emacs to point there somehow.

I understand what the move is trying to do, having SC better integrated with other tools to "manage" different lisp systems, but if I may offer some feedback, it does not seem clear for someone that is not well versed in this and I do fear it will become a bit more troublesome to install for someone that wants to give it a go out of curiosity. I don't mean that the move should not be implemented (it already is, and who am I to say otherwise), I am only pointing out that in my eyes, it became harder. I think some info could be added to start things easier for people not fluent in all these tools. So I offered to do a step by step video to get it running, when I finally get it running. (best way I can chip in with my two cents).

**Comment by JRSV** [comment]
I finally installed SC following [this](https://github.com/mdedwards/slippery-chicken/blob/master/install.md#long) instructive. However, I ran into many issues in my Debian 12 machine. Hopefully A.I. is perfect for me not to bother all of you guys with these rookie questions. So here goes a step by step description about my nightmare trip to enlightenment. Problems encountered where more of a technical vocabulary nature. ASDF was completely unknown, so the A.I. chat now is about silly questions like what the installation guide speaks of as obvious (eg. standard directories for ASDF/quicklisp). 

It is better of course that one does not have to worry about what IDE now the user picks, but rather you can access SC directly through SBCL in a terminal or use any IDE configured to look for LISP systems in a global directory. I must say though, all this made me nostalgic of the last script with the old install, that one was the easiest the installation process of SC has ever gone for me. 

I hope this post about really a non-issue helps someone that is into programming, but maybe not THAT into programming :P
for me, its back to normal now. 
thank you all


1. ASDF

I installed SBCL and ran the suggested command:
`(find :asdf *features*)`
with return:
`NIL`

so I went on to install ASDF. Acording to what I understand of the installation instructions. ASDF instructions states:

> First, make sure ASDF is checked out under a path registered to the source-registry, if that isn’t the case yet (see the manual). One place would be: 
~/.local/share/common-lisp/source/asdf/

I created that directory and placed ASDF in the folder. Now SBCL is suppose to find ASDF, but running the previous command delivers the same answer, however, if I eval
`(require 'asdf) `
as suggested by an IA, I get:
`("ASDF" "asdf" "UIOP" "uiop")
`
or:
`(asdf:asdf-version)`
which returns:
`"3.3.1"
`
so I will assume it is installed and the suggested:
`(find :asdf *features*)`
is perhaps only available in specific situations, or my system is missing something

2. Quicklisp

I downloaded the quicklisp.lisp and ran 
`sbcl --load /home/jrsv/.local/share/common-lisp/quicklisp.lisp`
and then:
`(quicklisp-quickstart:install)`
which installs QL,
running 
`(ql:quickload "quicklisp")`
returns
```
To load "quicklisp":
  Load 1 ASDF system:
    quicklisp
; Loading "quicklisp"

("quicklisp")
```
so quicklisp is installed and available

3. Dependencies
learned that this:
`in your ASDF/Quicklisp standard directory`
means this:
`~/.local/share/common-lisp/source/`
in my system. GOOD! :)
I continue to download dependencies succesfully, but beware with clm, the bastard unzips everything in the root, not a sub folder, I prefer to have it organized in directories. Moving on... I proceed to configuring slippery-chicken.
> On SBCL, for example, it is ~/.sbclrc by default,

nope... damn! lets fix this.
I go on and create it and move on...
loading SBCL starts everything but forgot to compile CLM, remember, CLM has some dependencies in linux (I think its "chs"), so installed 
`sudo apt-get install chs)`
and then back in CLM's directory
`./configure`
load SBCL from terminal again and voila!!
now lets get into emacs and 
`MX-slime`
and look!!! everything loads smoothly
once I am in CL, I call 
`CL-USER> (sc) `
and finally I am back in known territory.

**Comment by mdedwards** [comment]
Thanks for this Rafael. So it would seem that the greatest problem was the lack of ASDF in your lisp. hard to believe that's missing. Which version of SBCL are you using? I'm currently on  2.4.10. Maybe there's something wrong with your Linux package manager. Anyway glad you got through it all. All the best, Michael
